### ISSUE TITLE
[bug] 电源resume后自动startProxy

### ISSUE THREAD

**Issue by lslzl3000** [erguotou520/electron-ssr#103]
代理不启动时睡眠了，过会儿唤醒后发现无法上网~ 切换一下代理模式或者退出软件才行，查看代码发现，resume后无论之前代理是否开启，都自动startProxy修改了系统代理状态

> // 电源状态检测
  powerMonitor.on('suspend', () => {
    // 系统挂起时
    if (process.env.NODE_ENV === 'development') {
      console.log('power suspend')
    }
    stopTask()
    setProxyToNone()
    stopCommand(true)
  }).on('resume', () => {
    // 恢复
    if (process.env.NODE_ENV === 'development') {
      console.log('power resumed')
    }
    runWithConfig(currentConfig)
    startProxy()  // <==== 无论有没有启动代理，唤醒后都会会更改系统代理模式
    startTask(currentConfig)
  })

**Comment by lslzl3000** [comment]
其实挂起时，也不应该简单setProxyToNone，万一有其他程序在管控代理呢~~

**Comment by erguotou520** [comment]
嗯，第一个是bug，第2个没法准确判断，很多场景都会出现类似的场景，欢迎提交mr

**Comment by lslzl3000** [comment]
@erguotou520 第二个，我的建议是跟第一个逻辑应该一样，只有当前开启了代理，才set none，如果没开就别set none

> ...
if (currentConfig.enable) {
    setProxyToNone()
}
...
if (currentConfig.enable) {
    startProxy()
}

**Comment by erguotou520** [comment]
不排除 我先设置了代理，然后关掉代理，然后挂起了。此时代理也是这个应用修改的，但是因为你关掉了，所以我就不应该在挂起时清空代理？

**Comment by erguotou520** [comment]
请使用0.2.5版本测试
