### ISSUE TITLE
菜单无效

### ISSUE THREAD

**Issue by can-song** [erguotou520/electron-ssr#119]
点击任何菜单都没有反映

**Comment by can-song** [comment]
找到原因了， 这个默认设置的全是右键么，所有菜单只能使用右键点，能改成左键单击么？

**Comment by erguotou520** [comment]
你说的是哪个菜单？任务栏图标的那个菜单么？这个根据每个系统不同，而且其子菜单都是左键单击的。

**Comment by can-song** [comment]
我用的是Ubuntu16.04，左键单击右上角的图标会弹出下拉菜单，一开始我一直左键单击，每个按键都没用，后来无意间碰了下右键，发现每个按键都是右键触发

**Comment by erguotou520** [comment]
建议你看看其它类似软件是否有响应的问题，不存在说我专门设置成右键点击的

**Comment by Yourbee** [comment]
我这里也是，ubuntu16.04 运行的是appimage的0.2.3，小图标上的菜单右键有效，左键只有一级菜单有效。

**Comment by Xunzi229** [comment]
发现很多人有这个问题， 菜单点击无效
