### ISSUE TITLE
0.02版本不支持新的协议和混淆

### ISSUE THREAD

**Issue by gohomo** [erguotou520/electron-ssr#12]
希望能支持SSR新的协议和混淆，想自己打包，但按照教程步骤来没成功，错误如下：

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build:linux' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose stack Error: missing script: build:linux
4 verbose stack     at run (/usr/share/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/share/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/share/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/share/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/share/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:232:12
4 verbose stack     at /usr/share/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd /home/li/electron-ssr-develop
6 error Linux 4.4.0-64-lowlatency
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:linux"
8 error node v4.2.6
9 error npm  v3.5.2
10 error missing script: build:linux
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by erguotou520** [comment]
直接`npm run build`，系统会只打包你当前的系统对应的包，所以如果是要打包linux的，请在linux系统上运行该命令

**Comment by erguotou520** [comment]
`0.1.0`版本支持手动添加新的协议和混淆
