### ISSUE TITLE
Ubuntu 17.10 终端使用代理

### ISSUE THREAD

**Issue by secsilm** [erguotou520/electron-ssr#124]
请问如何在 Ubuntu 17.10 终端使用代理？我加了

```
export https_proxy="http://127.0.0.1:12333"
```

结果还是 ping 不通 www.google.com。

Chrome 和 Firefox 均可以正常使用代理。

**Comment by erguotou520** [comment]
ping 走的是icmp包，不是http 你试试 `curl www.google.com`

**Comment by lweo** [comment]
@erguotou520 curl: (7) Failed to connect to 127.0.0.1 port 12333: 拒绝连接
求解！
