### ISSUE TITLE
混淆协议不支持啊

### ISSUE THREAD

**Issue by xiaoxiaodek** [erguotou520/electron-ssr#13]
![2017-03-19 10 35 10](https://cloud.githubusercontent.com/assets/24558968/24077657/8ab811b2-0c90-11e7-9ef7-3a8c1c206314.png)

在linux客户端命令行好像连接上了，但最后翻不了，设置代理是直接在浏览器设置吗

**Comment by erguotou520** [comment]
你是说用这个工具翻不了但是python命令行可以？

**Comment by xiaoxiaodek** [comment]
这个gui服务协议选项没有auth_sha1_ v_4,然后我用python命令行操作好像成功了，但也连不上。。。浏览器代理设置我不会。。。

**Comment by erguotou520** [comment]
应该是我有段时间没更新的原因，新的协议还没支持

**Comment by erguotou520** [comment]
新的`0.1.0`版本已支持手动添加协议和混淆
