### ISSUE TITLE
openSuse风滚草系统下安装rpm包报错没什么能提供libappindicator，且忽略安装后点击图标无法打开应用

### ISSUE THREAD

**Issue by amosniu** [erguotou520/electron-ssr#132]
错误提示：没什么能提供libappindicator。且忽略安装后点击图标无法打开应用

**Comment by erguotou520** [comment]
请参考 [https://software.opensuse.org/download.html?project=X11%3AUnity&package=libappindicator](libappindicator) 安装`libappindicator`

**Comment by amosniu** [comment]
网址404错误阿，而且似乎没有这个东西而是后面加了个1，我是小白，问题简单希望别见笑

**Comment by amosniu** [comment]
你好，我从openSuse软件仓库尝试安装libappindicator，但是未安装成功，而且并未报什么错误，请问这是什么原因呢，搜索引擎查找也大多是libappindicator1或是libappindicator3的错误讲解，还望指正，谢谢！

**Comment by amosniu** [comment]
你好，还有一个疑问是安装好之后，第一次能打开，但是关闭软件后，就在也打不开了，点击图标并未弹出软件界面，这个是什么原因呢？还有是安装时候弹出提醒，签名校验失败，我的是openSuse风滚草系统。

**Comment by erguotou520** [comment]
因linux系统的一些特殊性，部分系统无法通过任务栏图标打开，此时请使用快捷键`ctrl+shift+w`打开。
至于签名校验我也不清楚

**Comment by amosniu** [comment]
你好，我是Linux小白，能详细说下ctrl+shift+w如何使用吗？是按住三个键然后点击图标还是其他操作方法呢，谢谢！

**Comment by amosniu** [comment]
你好，我是Linux小白，能详细解释下ctrl+shift+w快捷键如何使用吗？是设置快捷键？还是按住快捷键点击图标(似乎没用)，亦或是其他方法，谢谢！

**Comment by erguotou520** [comment]
在任意地方按这个组合键，应该就可以打开主页面，如果没有，那可能是快捷键冲突了

**Comment by amosniu** [comment]
请问可以自定义快捷键吗？如果可以，路径是默认是哪里呢，我是直接下载的rpm包安装的，谢谢。

**Comment by erguotou520** [comment]
暂时不支持自定义快捷键

**Comment by amosniu** [comment]
我卸载后按组合键并未有任何反应，猜测应该并没有被占用快捷键，但是安装后按组合键只会弹出一个通知消息在顶栏，之后会出现网络虽然连接，但浏览器却已经无法打开网页的情况，想请教下这个要怎么解决呢？

**Comment by amosniu** [comment]
能具体说明下如何操作吗，不是很懂，小白请谅解。。

**Comment by lweo** [comment]
@erguotou520 ctrl+shift+w是关闭浏览器的默认快捷键啊

**Comment by lweo** [comment]
@amosniu 你解决了吗？试试在终端里输入electron-ssr，我刚刚这么弄好了。。

**Comment by amosniu** [comment]
@lweo 我这边快捷键是可以打开的，倒是终端输入命令没反应

**Comment by erguotou520** [comment]
下个版本会加自定义快捷键
