### ISSUE TITLE
Linux下electron-ssr打开配置窗口一片空白

### ISSUE THREAD

**Issue by trancx** [erguotou520/electron-ssr#136]
OS： Linux  CentOS 7 

electron-ssr-0.2.3-x86_64

electron-ssr 打开界面之后一片空白，可以看到开发者工具，我在其他软件曾今重新安装过
electron 不知道是不是这个原因，之后就变成空白了，我决定重新卸载Npm,可是好像还是
有问题，就是右建图标->配置->选项配置，弹出的页面就是空白的。

因为不是监听的问题，所以我上传的是开发者日志。
renderer.js:33 iAlert
renderer.js:33 iAutoComplete
renderer.js:33 iButton
renderer.js:33 iButtonGroup
renderer.js:33 iCheckbox
renderer.js:33 iCol
renderer.js:33 iDropdown
renderer.js:33 iDropdownMenu
renderer.js:33 iDropdownItem
renderer.js:33 iForm
renderer.js:33 iFormItem
renderer.js:33 iIcon
renderer.js:33 iInput
renderer.js:33 iInputNumber
renderer.js:33 iMessage
renderer.js:33 iOption
renderer.js:33 iOptionGroup
renderer.js:33 iRow
renderer.js:33 iSelect
renderer.js:33 iTabs
renderer.js:33 iTabPane
renderer.js:33 iTable
renderer.js:33 iTag
renderer.js:33 iTree
renderer.js:33 iTooltip
renderer.js:33 iPoptip
renderer.js:33 iSpin
renderer.js:5 get init config data
renderer.js:5 Uncaught TypeError: Cannot read property 'length' of undefined
    at file:///tmp/.mount_electrhobKfX/app/resources/app.asar/dist/electron/renderer.js:5:100267
    at Array.filter (native)
    at a (file:///tmp/.mount_electrhobKfX/app/resources/app.asar/dist/electron/renderer.js:5:100241)
    at file:///tmp/.mount_electrhobKfX/app/resources/app.asar/dist/electron/renderer.js:5:100325
    at Array.filter (native)
    at a (file:///tmp/.mount_electrhobKfX/app/resources/app.asar/dist/electron/renderer.js:5:100241)
    at z.updateConfig (file:///tmp/.mount_electrhobKfX/app/resources/app.asar/dist/electron/renderer.js:33:94433)
    at file:///tmp/.mount_electrhobKfX/app/resources/app.asar/dist/electron/renderer.js:1:17375
    at file:///tmp/.mount_electrhobKfX/app/resources/app.asar/dist/electron/renderer.js:5:3481
    at Array.forEach (<anonymous>)
renderer.js:5 received view update:  ManagePanel undefined
renderer.js:5 received view update:  Options undefined

顺便能否告知那个APPIMAGE，具体安装在哪里，我准备全部删除然后重新安装试一试
可是发现似乎找不到

**Comment by erguotou520** [comment]
你是运行的开发环境？可以直接使用release版本啊。APPIMAGE的使用方法请先搜索

**Comment by trancx** [comment]
我的就是APPImage 原来是没有问题的 后来发现打开之后就空白了。

**Comment by erguotou520** [comment]
那建议你换成对应的linux发包版,deb这种的

**Comment by trancx** [comment]
我还想请问一下，就是我的配置数据是在哪里的？ 我重新打开一个新的appimage发现原来的数据还是在，我想清空一下，能给个提示吗

**Comment by trancx** [comment]
我还想请问一下，就是我的配置数据是在哪里的？ 我重新打开一个新的appimage发现原来的数据还是在，我想清空一下，能给个提示吗

**Comment by trancx** [comment]
我还想请问一下，就是我的配置数据是在哪里的？ 我重新打开一个新的appimage发现原来的数据还是在，我想清空一下，能给个提示吗

**Comment by erguotou520** [comment]
一般都是在`~/.config/electron-ssr`，这些信息在readme中都有，麻烦使用之前先看下说明

**Comment by trancx** [comment]
不好意思， REDAME没看见有说配置文件存在哪里， 我自己也找到了。  只需要把所有的配置文件都删了就OK， 在 ～/.config/electron-ssr  然后重新打开image自动安装就正常了，如果不行应该还要把electron都删了
