### ISSUE TITLE
Linux 单击程序图标启动默认挂后台？最小化后状态栏没图标。。

### ISSUE THREAD

**Issue by lweo** [erguotou520/electron-ssr#138]
ctrl+shift+W 调出程序后最小化后没有小图标
## Your os
Linux version 3.13.0-132-generic (buildd@lcy01-19) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) )

**Comment by erguotou520** [comment]
请先参考FAQ尝试解决

**Comment by lweo** [comment]
@erguotou520 没直接解决，通过终端运行的，不过怎么在终端里结束？按ctrl+c，提示crush，之后重启电脑就进不了桌面了，不知道跟这软件有没有关系，查看.xsession-errors，有相关报错信息。。

root@k-E400:/home/k# cat .xsession-errors.old
fcitx 使用的 script 从 run_im 启动。
init: at-spi2-registryd main 进程结束, 重新产生
init: at-spi2-registryd main 进程结束, 重新产生
init: at-spi2-registryd main 进程结束, 重新产生
init: at-spi2-registryd main 进程结束, 重新产生
init: at-spi2-registryd main 进程结束, 重新产生
init: at-spi2-registryd main 进程结束, 重新产生
init: at-spi2-registryd main 进程结束, 重新产生
init: at-spi2-registryd main 进程结束, 重新产生
init: at-spi2-registryd main 进程结束, 重新产生
init: at-spi2-registryd main 进程结束, 重新产生
init: at-spi2-registryd 重新建立过快，停止
init: update-notifier-crash (/var/crash/_opt_electron-ssr_electron-ssr.0.crash) main 进程 (4258)以状态 1 结束
init: gnome-session (Unity) main 进程 (4419)以状态 1 结束
init: logrotate main 进程 (4217)已经被TERM 信号杀死
init: update-notifier-release main 进程 (4288)已经被TERM 信号杀死
init: 从告知的D-Bus总线断开

**Comment by erguotou520** [comment]
不需要在终端运行啊 我是让你看图标的问题啊 为什么会crash

**Comment by lweo** [comment]
开始菜单里图标，单击启动无反应（实际上已启动，只是没出现窗口，状态栏也没小图标），只能在终端里启动。

**Comment by bitxinyu** [comment]
我也出现同样的问题，安装chrome后问题解决了，楼主可以试一下。

**Comment by erguotou520** [comment]
请参考 #230
