### ISSUE TITLE
关于以后更新的建议

### ISSUE THREAD

**Issue by OneWizard** [erguotou520/electron-ssr#14]
可以考虑成直接调用py版吗？
思路类似这个autohotkey的ss-libev小启动器，改改也能用来调用任意命令行同类软件，http://www.chaizi.org/1495.html
可惜autohotkey是win下的，不能跨平台
这样以后只要直接覆盖后端就行了
至少不用花太多精力维护了

（其实是我试了几次没编译成功electron-rss。。。）

**Comment by erguotou520** [comment]
你的意思是可以添加个选择本地python项目的功能？

**Comment by OneWizard** [comment]
我的意思是把ssr的py后端独立出来，不整合进程序，毕竟本身py就是跨平台的，然后electron-ssr的协议、加密列表改成高级设置里可以编辑添加新协议和加密的
这样的话，ssr更新添加新协议或者加密后，只需要覆盖掉旧ssr后端，然后在协议列表里添加新的就可以了

**Comment by erguotou520** [comment]
嗯，明白，后面会考虑做成这样。
你编译报错的错误信息可以贴下

**Comment by erguotou520** [comment]
新的`0.1.0`版本已支持手动添加协议和混淆以及手动指定`python`的目录
