### ISSUE TITLE
windows系统路径中的空格导致系统命令无法被正确执行

### ISSUE THREAD

**Issue by YECHUNAN** [erguotou520/electron-ssr#142]
## Your os
Windows 10

## The version of electron-ssr
v1.8.7

## What's the problem

系统用户名中存在空格，导致指向系统目录下可执行文件无法被正确执行。
![capture](https://user-images.githubusercontent.com/16599672/41273400-2acc9656-6dce-11e8-9599-ff7d33ba76bc.PNG)

**Comment by erguotou520** [comment]
emmmmm~

**Comment by erguotou520** [comment]
请使用0.2.5版本测试
