### ISSUE TITLE
是否可以加入 ia32 的包

### ISSUE THREAD

**Issue by HZoi-WildRage** [erguotou520/electron-ssr#144]
## Your os

Windows And Ubuntu

## What's the problem

我经常使用32位系统。
能不能考虑添加32的包， linux & Win

**Comment by erguotou520** [comment]
太拖时间了，之前win32有的，但是构建过程不够友好，考虑到大部分都是64的系统，所以就去掉32了。建议你fork后本地构建或者用ci构建下

**Comment by HZoi-WildRage** [comment]
是这样的， 我对electron-vue 不是很熟悉。  
请问您能不能发一个构建的配置。

**Comment by erguotou520** [comment]
可以直接参考根目录下的`.travis.yml`文件（适用mac和linux的构建）以及`appveyor.yml`文件（适用于windows的构建）

**Comment by erguotou520** [comment]
0.2.5版本开始将只打包win32位的，其它都是64位
