### ISSUE TITLE
是不是只能用GUI系统才能使用

### ISSUE THREAD

**Issue by coldeve** [erguotou520/electron-ssr#147]
我尝试用代码控制失败了
——————抱歉，可能是没描述清楚——————
我下载deb后，因为系统是精简版，为了节省资源没有安装gui界面，发现用./ 启动没有任何反应，是不是这个只支持在GUI界面使用，在纯shell界面里无法使用。

**Comment by erguotou520** [comment]
什么意思？请描述清楚

**Comment by coldeve** [comment]
——————抱歉，可能是没描述清楚——————
我git clone后，因为系统是精简版，为了节省资源没有安装gui界面，发现用./ 启动没有任何反应，是不是这个只支持在GUI界面使用，在纯shell界面里无法使用。

还有 在raspberry pi（树莓派）上编译失败 是不是不支持arm？

**Comment by erguotou520** [comment]
是的，命令行还是用`python`版本吧，树莓派还真没试过，不过你确定要在树莓派那小机器上用么？

**Comment by coldeve** [comment]
已找到树莓派上使用的方法，Python版本编译而成，占用不高。
还是谢谢了

**Comment by toytag** [comment]
@coldeve May I ask what app (the nice python version) that you are currently using on raspberry pi?

**Comment by jth445600** [comment]
我也想知道你是如何在树莓派上使用的？

**Comment by ziyoo365** [comment]
可以分享一下树莓派上怎么安装使用吗？我的是树莓派3b+，下载了发布的arm版本就是运行不起来，解压了双击软件无法打开
