### ISSUE TITLE
编译又有进步，已经到最后一步，最终还是出错

### ISSUE THREAD

**Issue by gohomo** [erguotou520/electron-ssr#15]
Building electron app(s)...

No native production dependencies
Packaging for linux x64 using electron 1.6.2 to builds/linux-unpacked
Building tar.gz
Building rpm
Build error: Error: Exit code: 1. Command failed: /home/li/.cache/electron-builder/fpm/fpm-1.6.3-2.3.1/fpm -s dir -t rpm --architecture amd64 --name electron-ssr --force --after-install /tmp/electron-builder-Za4HwR/0-2-after-install --after-remove /tmp/electron-builder-Za4HwR/0-3-after-remove --description ShadowsocksR client using electron --maintainer erguotou <erguotou525@gmail.com> --vendor erguotou <erguotou525@gmail.com> --version 0.0.2 --package /home/li/下载/electron-ssr-develop/builds/electron-ssr-0.0.2.rpm --url https://github.com/erguotou520/electron-ssr --rpm-os linux /home/li/下载/electron-ssr-develop/builds/linux-unpacked/=/opt/ShadowsocksR客户端 /home/li/下载/electron-ssr-develop/build/icons/128x128.png=/usr/share/icons/hicolor/128x128/apps/electron-ssr.png /home/li/下载/electron-ssr-develop/build/icons/16x16.png=/usr/share/icons/hicolor/16x16/apps/electron-ssr.png /home/li/下载/electron-ssr-develop/build/icons/24x24.png=/usr/share/icons/hicolor/24x24/apps/electron-ssr.png /home/li/下载/electron-ssr-develop/build/icons/256x256.png=/usr/share/icons/hicolor/256x256/apps/electron-ssr.png /home/li/下载/electron-ssr-develop/build/icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/electron-ssr.png /home/li/下载/electron-ssr-develop/build/icons/48x48.png=/usr/share/icons/hicolor/48x48/apps/electron-ssr.png /home/li/下载/electron-ssr-develop/build/icons/64x64.png=/usr/share/icons/hicolor/64x64/apps/electron-ssr.png /home/li/下载/electron-ssr-develop/build/icons/96x96.png=/usr/share/icons/hicolor/96x96/apps/electron-ssr.png /tmp/electron-builder-Za4HwR/0-1-ShadowsocksR客户端.desktop=/usr/share/applications/electron-ssr.desktop

{:timestamp=>"2017-03-28T13:24:21.705064+0800", :message=>"Need executable 'rpmbuild' to convert dir to rpm", :level=>:error}

这是什么错误呢，builds文件夹里有压缩包，但解压后执行出现错误

**Comment by erguotou520** [comment]
请参考这篇文章 https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux
构建任务里有几个打包，而打包依赖于系统上安装的打包命令

**Comment by gohomo** [comment]
明白了，打包的依赖没解决而已，另外一个是我打包好后，有最新的混淆，但不能使用，还出现以下错误 ：
Uncaught Exception:
TypeError: Cannot read property 'stdout' of undefined
    at execCmd (/home/li/ssr/resources/app.asar/client.js:22:8)
    at Object.module.exports.stop (/home/li/ssr/resources/app.asar/client.js:53:5)
    at Object.module.exports.run (/home/li/ssr/resources/app.asar/client.js:62:18)
    at EventEmitter.trayEvent.on (/home/li/ssr/resources/app.asar/electron.js:114:14)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at toggleEnable (/home/li/ssr/resources/app.asar/tray.js:13:9)
    at MenuItem.click (/home/li/ssr/resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/home/li/ssr/resources/electron.asar/browser/api/menu.js:121:15)

**Comment by erguotou520** [comment]
呃~ 发现21行少了`child = exec(command)`

**Comment by erguotou520** [comment]
新的`0.1.0`版本已支持手动添加协议和混淆
