### ISSUE TITLE
httpPorxy Problem

### ISSUE THREAD

**Issue by happy163** [erguotou520/electron-ssr#153]
My OS: Ubuntu18.04
我开启了electron-ssr之后，在选项里打开了局域网共享，httpProxy监听的还是127.0.0.1
尝试了重启electron-ssr或者系统，都还是127.0.0.1，没有发生变化
这样导致局域网内的用户无法连接
不知道是我的操作问题还是系统关系

**Comment by erguotou520** [comment]
你不要瞎想，这是代码问题 😭

**Comment by erguotou520** [comment]
#117

**Comment by happy163** [comment]
好的吧，我下的是release的，那只能自己构建一份了

**Comment by erguotou520** [comment]
请使用0.2.5版本测试
