### ISSUE TITLE
Ubuntu 17.04任务栏不显示小图标

### ISSUE THREAD

**Issue by HuangBoHong** [erguotou520/electron-ssr#17]
求解
![12](https://cloud.githubusercontent.com/assets/11132087/26751002/2fec963c-4862-11e7-86fe-e230c4b78201.png)

**Comment by erguotou520** [comment]
咦~ 好奇怪 开发版本也会么

**Comment by wudimenghuan** [comment]
16.04 同样没有，而且打开一个之后不出现界面了，点很多次，出现很多进程

**Comment by erguotou520** [comment]
抽空我来看下

**Comment by edwinhuish** [comment]
是否没有用sudo？我现在这个不知道为什么每次都需要用sudo权限才能正常启动

**Comment by edwinhuish** [comment]
我的ubuntu 17.04 正常显示
![2017-07-09 09-53-30](https://user-images.githubusercontent.com/5207925/27990537-96ad4bd2-648c-11e7-860f-918f3f09e5f8.png)

不过需要用sudo启动，并且报下面这个错误。
![2017-07-09 09-50-17](https://user-images.githubusercontent.com/5207925/27990536-9673d0b4-648c-11e7-9bde-d0447409e654.png)

**Comment by erguotou520** [comment]
请测试`0.1.1`版本，谢谢

**Comment by lipeng1a** [comment]
谁能教一下我怎么装，刚开始用ubuntu系统

**Comment by lipeng1a** [comment]
我的也不行

**Comment by lipeng1a** [comment]
@edwinhuish 怎么用sudo，我直接装的，都不知道装在哪？搜了一下local.py，没有ssr下的。最后能不能指导一下我怎么装

**Comment by edwinhuish** [comment]
@lipeng1a 你可以看一下我上面的截图

**Comment by Runninghole** [comment]
使用sudo 也没法显示小图标
sudo /opt/ShadowsocksR客户端/electron-ssr
Config file's path: /home/zhuwendong/.config/electron-ssr/shadowsocksr.json
/usr/local/shadowsocksr/shadowsocks/local.py
mainWindow opened

**Comment by peter17ji** [comment]
已经确认最新版在17.04不能显示图标

**Comment by erguotou520** [comment]
请大家使用最新的`0.2.0`版本，小飞机应该有了
