### ISSUE TITLE
Mac端bug

### ISSUE THREAD

**Issue by HanXiaoTeng** [erguotou520/electron-ssr#172]
Mac端
版本号:0.2.3

bug:
1.PAC无法更新，更新失败
2.系统代理模式选择PAC无法代理，选择全局模式可以代理
3.弹窗 进程7939可能无法关闭 请手动关闭

**Comment by cnccn** [comment]
的确存在该问题，作者可否修复？是不是默认更新Pac的地址失效了？可否让用户手工输入pac的地址

**Comment by erguotou520** [comment]
是因为地址被墙了，在新版本中已修复，但最近没有时间改

**Comment by erguotou520** [comment]
请使用0.2.5版本测试
