### ISSUE TITLE
Ubuntu 下点击没有反应

### ISSUE THREAD

**Issue by Xunzi229** [erguotou520/electron-ssr#174]
## Your os
Ubuntu 16.04

## The version of electron-ssr
electron-ssr_0.2.3_amd64.deb

## What's the problem
打开electron-ssr后 ，点击 系统模式，或者编辑服务器，等里面所有功能，都没有啥反应
但是偶尔也能打开

## App log here
并没有什么错误日志， 只是 大部分时候 都是按键失灵状态

**Comment by erguotou520** [comment]
同样的问题请不要新开issue #119
