### ISSUE TITLE
PAC更新失败，来催更了

### ISSUE THREAD

**Issue by AnthonyZhai** [erguotou520/electron-ssr#178]
https://softs.fun/Other/pac.txt下载失败，服务器不可用

**Comment by AnthonyZhai** [comment]
提供一个可用的PAC地址：https://softs.loan/Other/pac.txt

**Comment by cnccn** [comment]
好像没有在软件里找到可以修改PAC地址的地方啊

**Comment by AnthonyZhai** [comment]
@cnccn 在源码的src/main/pac.js里第27行可以修改，但是我编译失败了，如果你成功编译可以告知我

**Comment by gujiangjiang** [comment]
Fixed.

**Comment by AnthonyZhai** [comment]
Great & thx
