### ISSUE TITLE
可否更新下支持新的协议以及ssr订阅？

### ISSUE THREAD

**Issue by lsblk** [erguotou520/electron-ssr#18]

**Comment by erguotou520** [comment]
ssr订阅是什么？不是很懂，麻烦解释下

**Comment by lsblk** [comment]
![image](https://user-images.githubusercontent.com/11588373/27291390-a6c148a6-5542-11e7-8f2f-6d4359424198.png)
是ssr windows 还有 安卓版的新特性，支持通过链接订阅ssr节点，打开安卓或win最新版就可以看到有订阅选项，方便从ssr提供商那里自动更新节点

**Comment by erguotou520** [comment]
有没有节点生成规则的说明？这样我才可以做解析

**Comment by erguotou520** [comment]
新的`0.1.0`版本已支持手动添加协议和混淆。关于订阅功能，如果有相关的文档说明还是可以做到的

**Comment by lsblk** [comment]
谢谢。你看一下这个是不是你需要的文档。https://github.com/breakwa11/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3

**Comment by erguotou520** [comment]
ok,下个版本加进去
