### ISSUE TITLE
希望能够修复PAC的问题

### ISSUE THREAD

**Issue by gujiangjiang** [erguotou520/electron-ssr#184]
原PAC的域名已经更换了。。。

这个是新的域名，现在只有全局可用，PAC无法连接，希望更新

旧：https://softs.fun/Other/pac.txt
新：https://softs.loan/Other/pac.txt

**Comment by AnthonyZhai** [comment]
你可以修改[这里](https://github.com/erguotou520/electron-ssr/issues/178#issuecomment-414583885)然后自己编译一下，但是我失败了如果你编译成功请告知我

**Comment by gujiangjiang** [comment]
Fixed.
