### ISSUE TITLE
使用 develop 版本编译、使用出现的问题。

### ISSUE THREAD

**Issue by HougeLangley** [erguotou520/electron-ssr#19]
编译，按照主页提供的方法是编译并不方便。

首先我使用的系统是 Linux MInt 18.2 KDE Beta 版本，基于Ubuntu 16.04，首先要解决的问题是npm和nodejs的问题，需要到nodejs官网使用最新的8.x版本的npm进行编译，否则使用系统默认repo中的npm无法编译，过程一直提示nodejs版本过低。

然后，主页现实 npm run build:linux 给我们这些伸手党一种误解，直接复制粘贴，结果出现没有build:linux脚本错误。个人觉得直接 npm run build 就妥了。

其次，最新版本在我这里运行后主控台无法正常显示，启动软件后一闪，任务了留了一个图标，编辑服务器以后点击确定，关闭窗口，electron-ssr彻底挂了，再启动，没有保存我输入的服务器信息。

最后，混淆协议中没有 tls1.2_ticket_fastauth

目前遇到这四个问题。期待解决。

**Comment by erguotou520** [comment]
1. `node`建议使用`nvm`进行管理安装
2. README文档错误
3. 多试几次？这个问题我也不确定是啥情况- -!
4. 收到

**Comment by HougeLangley** [comment]
谢谢反馈～

**Comment by erguotou520** [comment]
最近正在开发新版本，有些问题会得到解决

**Comment by HougeLangley** [comment]
非常感谢，如果有更新我会及时pull并测试～

**Comment by HougeLangley** [comment]
added 16 packages in 2.445s
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN electron-devtools-installer@1.1.5 requires a peer of electron-prebuilt@^1.2.1 but none was installed.
npm WARN electron-ssr@0.1.0 No repository field.

**Comment by erguotou520** [comment]
新的`0.1.0`版本已支持手动添加协议和混淆。欢迎尝试新版本 😿

**Comment by erguotou520** [comment]
issue先关了，有问题再开
