### ISSUE TITLE
安装新版后出现这样的错误提示（MAC上使用）

### ISSUE THREAD

**Issue by zhouhounan** [erguotou520/electron-ssr#20]
![image](https://user-images.githubusercontent.com/17348292/27505400-74ff61da-58d1-11e7-85da-c44559827094.png)

**Comment by erguotou520** [comment]
怎么操作的跟我说下

**Comment by erguotou520** [comment]
理论上该问题也在`0.1.1`版本中修复，麻烦测试下告知结果

**Comment by erguotou520** [comment]
issue先关了，有问题再开
