### ISSUE TITLE
大佬，Ubuntu 16.04 PAC代理模式无法翻墙，只有全局的能用

### ISSUE THREAD

**Issue by WangZhonglei** [erguotou520/electron-ssr#201]
PAC也更新成功了，我也按网上的，自己用genpac生成了一个pac文件，指定了目录，一重启路径就又变成软件指定的127.0.0.1:2333，，我自己生成的pac也有端口号吗？咋指向它

**Comment by erguotou520** [comment]
替换掉原文件 不要指定路径

**Comment by WangZhonglei** [comment]
> 替换掉原文件 不要指定路径

多谢，ok了。

**Comment by lawler61** [comment]
我也全局才能访问，怎么生成pac文件呀，指定的目录又在哪里的呢 @WangZhonglei
