### ISSUE TITLE
OSX10.9.5 report

### ISSUE THREAD

**Issue by 2ndMessiah** [erguotou520/electron-ssr#21]
首先感谢dev的辛勤劳作。10.9.5已经不再作为ssr两个osx分支的支持系统了，之前我是直接用alfred+ssr-python跑起来，体验还行，但是还是想用一个有漂亮gui的。

看到作者的app眼前一亮，跑起来也ok，试了一下，提出以下几个意见：
1、在task tray菜单里面集成pac\全局等模式的支持
2、可以以daemon（？）模式运行。打开app之后还在dock上驻留，只留task tray上一个就好啊~

加油！keep your good work!

**Comment by erguotou520** [comment]
1. “pac/全局模式“这种是怎么搞的，原理是啥？
2. 我回去再研究研究，是什么情况

**Comment by 2ndMessiah** [comment]
全局和pac在osx里面我是直接用bash搞定的。。比如指定一个pac文件的shell：
#重置proxy状态
echo “password" | sudo -S networksetup -setwebproxystate Wi-Fi off 
echo “password" | sudo -S networksetup -setsocksfirewallproxystate Wi-Fi off 
echo “password" | sudo -S networksetup -setautoproxystate Wi-Fi off 
#设置为pac文件
echo "5678" | sudo -S networksetup -setautoproxystate Wi-Fi on 
echo "5678" | sudo -S networksetup -setautoproxyurl Wi-Fi https://raw.githubusercontent.com/2ndMessiah/PAC/master/proxy.pac;
killall Terminal

#设置为全局代理
echo “passwd" | sudo -S networksetup -setsocksfirewallproxystate Wi-Fi on
echo “passwd" | sudo -S networksetup -setsocksfirewallproxy Wi-Fi 127.0.0.1 1080
killall Terminal

可以参考一下shadowsocksX的实现方法吧··这我就不太懂了 ^ ^
在 2017年6月26日，下午1:38，erguotou <notifications@github.com> 写道：

**Comment by erguotou520** [comment]
好高级的样子，但是我不太懂啊 。。。

**Comment by 2ndMessiah** [comment]
osx下面在terminal下就是这样。。我相信你的dev 感谢 /抱拳
在 2017年6月26日，下午2:35，erguotou <notifications@github.com> 写道：

**Comment by erguotou520** [comment]
dev是什么意思？开发者？

**Comment by 2ndMessiah** [comment]
是啊~
在 2017年6月27日，上午9:34，erguotou <notifications@github.com> 写道：

**Comment by wle6** [comment]
OSX10.9.5下怎么使用，能写个操作说明吗？

**Comment by erguotou520** [comment]
`0.1.1`版本已经可以不在dock中显示了

**Comment by 2ndMessiah** [comment]
谢谢大大的辛勤劳作。macbook放学校了现在在家里不能测试。。开学之后会feedback给你

2017-07-27 14:30 GMT+08:00 erguotou <notifications@github.com>:

**Comment by erguotou520** [comment]
ok

**Comment by wle6** [comment]
0.1.2版终于在OSX10.9.5上使用成功，希望后续版本能增加订阅功能。

**Comment by erguotou520** [comment]
@2ndMessiah 在新版中已加入pac，但是使用的工具不支持OSX10.11以下版本
dock的问题应该也没有

@wle6 订阅和导入也有了

**Comment by 2ndMessiah** [comment]
感谢大佬辛勤工作！
--
从Mail.Ru的Android专用app所发送 星期三, 31 一月 2018, 01:55下午 +08:00 发件人 erguotou  notifications@github.com :
