### ISSUE TITLE
如何只构建 linux-unpacked 而不打包？

### ISSUE THREAD

**Issue by guoyunhe** [erguotou520/electron-ssr#211]
现在的构建脚本会构建所有类型的包，非常耗时，弱一些的电脑吃不消。能不能提供一个选项，只构建 linux-unpacked 而不打包 deb, rpm, AppImage 什么的？谢谢！

**Comment by erguotou520** [comment]
因为我针对不同的用户肯定会打包成不同的，如果你自己有需求可以直接修改打包文件，修改
https://github.com/erguotou520/electron-ssr/blob/master/.electron-vue/release.js#L118
