### ISSUE TITLE
Ubuntu pac换一个网上的即可使用

### ISSUE THREAD

**Issue by sunmker** [erguotou520/electron-ssr#212]
## Your os

ubuntu 18.04
## The version of electron-ssr

自带的pac.txt无法使用，换一个源就可以解决
## What's the problem

右键 链接另存为https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/other/pac.txt 
这个文件  
### ### 然后覆盖到「~/.config/electron-ssr/」文件夹下即可使用
```
 mv Downloads/pac.txt ~/.config/electron-ssr/
```

**Comment by kingskill** [comment]
的确如此。

不晓得electron自己的那个pac出了什么问题？

**Comment by shijiantian** [comment]
@kingskill 对比了一下，两个文件的不同就是一些转义字符，应该是自带的pac需要转义的地方没转义导致出错。

**Comment by erguotou520** [comment]
已修改代码并重新生成pac文件，请大家测试下

**Comment by luo-chuan** [comment]
既然作者更新了，那明天测试一下新版

**Comment by kingskill** [comment]
老大，release还是之前的0.24版？还是说只是更新了源代码？

**Comment by luo-chuan** [comment]
亲测此方法有效，帮顶

**Comment by HanXiaoTeng** [comment]
@erguotou520 Manjaro Linux下的pac文件还是不好使 无论点击更新还是不更新 只有全局模式可以代理

**Comment by erguotou520** [comment]
好像是因为travis ci那边构建的脚步还是老脚本。。。

**Comment by evhh** [comment]
ubuntu 18.04/chrome 无论是楼主给的，还是11-03更新的，都不行。

**Comment by erguotou520** [comment]
再重新更新下，直接用逗比根据地提供的脚本运行的结果和它自身项目里生成的不一样，简单修改了下脚本，已重新生成
