### ISSUE TITLE
ubuntu 16.04打开一次后就不能再打开了

### ISSUE THREAD

**Issue by ATFieldBeast** [erguotou520/electron-ssr#214]
## Your os

Ubuntu 16.04（Ubuntu Budgie 16.04)
## The version of electron-ssr

0.2.4_amd64
## What's the problem

就装好之后第一次打开可以打开，x掉后就不能打开了（点击图标没有反应），卸载重装也不行了
（还有就是想请问默认下载的那个ssr python在哪个默认路径，我有自己装的不过当时想试一下就点了下载，结果现在打不开了不知道在哪，想删掉它)
## App log here

无法打开

**Comment by erguotou520** [comment]
请使用快捷键`Ctrl+Shift+W`打开
默认路径请在主界面打开后使用`Ctrl+Shift+B`快捷键打开菜单，设置里有
另外可以通过搜索Issue 看看别人怎么解决图标无法显示的问题的
