### ISSUE TITLE
macOS 的 PAC 模式不生效（全局模式可以）

### ISSUE THREAD

**Issue by kyan001** [erguotou520/electron-ssr#216]
## Your os
macOS 10.14 Mojave

## The version of electron-ssr
0.2.4

## What's the problem
macOS 的 PAC 模式不生效，切换至 PAC 模式后和未打开代理是一样的。
用全局模式是可以生效的。
已经全局模式更新 PAC。

**Comment by wxdjs** [comment]
这个好像是pac文件有问题，自己下载个别的pac文件就可以了

**Comment by kyan001** [comment]
> 这个好像是pac文件有问题，自己下载个别的pac文件就可以了

我下载了个别的 PAC 文件，可是怎么替换啊？我看 Ubuntu 是放到 `~/.config/electron-ssr/` 里，可是 macOS 里没有这个文件夹诶。。

**Comment by HanXiaoTeng** [comment]
@erguotou520 当前时间的PAC文件还是不能代理，只能用全局模式，测试替换PAC文件后可以代理。系统Manjaro Linux

**Comment by yangyuanming** [comment]
> pac文件已更新，请重新下载pac文件

我找了shadowsockx-ng的pac文件(gfwlist.js)改名为pac.txt替换，pac模式依然不生效。shadowsockx-ng下pac正常。

**Comment by erguotou520** [comment]
再重新更新下，直接用逗比根据地提供的脚本运行的结果和它自身项目里生成的不一样，简单修改了下脚本，已重新生成

**Comment by yangyuanming** [comment]
> 再重新更新下，直接用逗比根据地提供的脚本运行的结果和它自身项目里生成的不一样，简单修改了下脚本，已重新生成

没问题了，O(∩_∩)O谢谢
