### ISSUE TITLE
关于linux mint 19中安装后全局代理后本地连接路由的问题

### ISSUE THREAD

**Issue by wxdjs** [erguotou520/electron-ssr#218]
默认状态下
linux mint 19，安装后点击软件界面上自动安装ssr，默认设置全局或自动pac，浏览器chrome可以上网，firefox只能全局上网，此时已经勾选http代理，但是系统中http，https，ftp中都是空的，默认端口号不是软件中设定的
修改系统代理填入正确的地址和端口，才可以上网
当全局代理时，连接不上路由器，比如192.168.1.1，需要自动或不代理，系统防火墙关闭的

**Comment by erguotou520** [comment]
勾选http代理只是启动http代理服务，并不会修改系统代理设置
全局代理连不上本地地址应该是正常的

**Comment by wxdjs** [comment]
谢谢回复，另外请问 你的TG群邀请链接好像失效了

**Comment by erguotou520** [comment]
之前开放一段时间，现在暂时关闭
