### ISSUE TITLE
0.1.0 linux版执行的命令不全

### ISSUE THREAD

**Issue by lsblk** [erguotou520/electron-ssr#22]
如图，我输入了服务商提供的ssr链接，图形界面显示的正常，但是执行的命令里没有协议的选项，导致ssr默认使用origin协议，
![default](https://user-images.githubusercontent.com/11588373/27868998-1e9860fe-61d1-11e7-9ab7-f75c47af2fb8.png)

**Comment by erguotou520** [comment]
你这么一说我重新看了下文档，确实没找到。。。
https://github.com/breakwa11/shadowsocks-rss/issues/835

**Comment by lsblk** [comment]
楼主可否更新下编译好的文件？小白不会编译啊。。

**Comment by erguotou520** [comment]
抽空升级下

**Comment by erguotou520** [comment]
修了后再关

**Comment by edwinhuish** [comment]
为何不直接将 ``` ~/.config/electron-ssr/shadowsocksr.json ``` 里的 ``` configs ``` 拆分为各个配置文件，然后启动时读取呢？这样配置更全。

**Comment by erguotou520** [comment]
一样的，没什么区别，读一个文件总比读多个文件好吧，而且`c#`客户端也是这么做的啊

**Comment by erguotou520** [comment]
`0.1.1`版本中已追加新参数

**Comment by erguotou520** [comment]
issue先关了，如果有问题再开
