### ISSUE TITLE
希望能加上aes-256-gcm

### ISSUE THREAD

**Issue by Sniper970119** [erguotou520/electron-ssr#221]

**Comment by erguotou520** [comment]
自行添加，在设置里，只要你的ssr支持

**Comment by Sniper970119** [comment]
但是你们这个在我这好像不能用。。总是把我本机代理改成127.0.0.1:1080 ，然后就是代理服务器拒绝访问。。反正就是。。用不了，不知道是怎么回事

**Comment by Sniper970119** [comment]
> 
> 
> 自行添加，在设置里，只要你的ssr支持
但是你们这个在我这好像不能用。。总是把我本机代理改成127.0.0.1:1080 ，然后就是代理服务器拒绝访问。。反正就是。。用不了，不知道是怎么回事
