### ISSUE TITLE
PAC mode is not functional in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Thesharing** [erguotou520/electron-ssr#222]
## Your os
Ubuntu 16.04 LTS

## The version of electron-ssr
v0.2.4

## What's the problem
在Electron-SSR的菜单中选择PAC模式会将系统代理切换至自动（127.0.0.1:2333/proxy.pac），使用该PAC文件Chrome无法正常访问Google；选择全局模式会将系统代理切换至手动（HTTP代理为127.0.0.1:12333，socks5代理为127.0.0.1:1080），在这种情况下Chrome可以正常访问Google；最后使用GenPac基于GFWList生成PAC文件：
```
genpac --proxy="SOCKS5 127.0.0.1:1080" --gfwlist-proxy="SOCKS5 127.0.0.1:1080" -o autoproxy.pac --gfwlist-url="https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt"
```
将系统代理切换至自动（/home/thesharing/autoproxy.pac），可以正常使用Chrome访问Google。个人认为PAC文件可能存在问题，建议换成用GenPac基于GFWList生成PAC文件。

## App log here

> 2018-10-29 00:53:08 <debug> main.js:1 () start download pac
> 2018-10-29 01:13:19 <info> main.js:1 () file ensured
> 2018-10-29 01:13:19 <info> main.js:1 (u) Register shortcut: toggleMenu, CommandOrControl+Shift+B
> 2018-10-29 01:13:19 <debug> main.js:1 (o) run command: python /home/thesharing/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s us-2.mitsuha-node.com -p 443 -m aes-256-ctr -O auth_aes128_md5 -G 13590:4zM6Cg -o tls1.2_ticket_auth -g HK2SCH130fb5a413590.wns.windows.com -b 0.0.0.0 -l 1080
> 2018-10-29 01:13:19 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 0.0.0.0:2333
> 2018-10-29 01:13:19 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 0.0.0.0:12333
> 2018-10-29 01:13:20 WARNING  shell.py:110 warning: local set to listen on 0.0.0.0, it's not safe
> 2018-10-29 01:13:20 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
> 2018-10-29 01:13:20 INFO     local.py:50 local start with <Deleted by me>
> 2018-10-29 01:13:20 INFO     local.py:54 starting local at 0.0.0.0:1080
> 2018-10-29 01:13:20 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]
> 2018-10-29 01:13:32 <debug> main.js:1 () start download pac

**Comment by erguotou520** [comment]
有重新更新过PAC文件么？现在的PAC文件生成规则是从doubi那边拉的

**Comment by Thesharing** [comment]
> 有重新更新过PAC文件么？现在的PAC文件生成规则是从doubi那边拉的

我是手动用最新版的Release文件替换之后更新了Pac，然后也能看到proxy.pac，但是没有办法正常访问Google。

[proxy.pac.zip](https://github.com/erguotou520/electron-ssr/files/2524078/proxy.pac.zip)

**Comment by erguotou520** [comment]
再更新下pac，之前的pac文件内容有问题
