### ISSUE TITLE
添加订阅后覆盖其他节点信息

### ISSUE THREAD

**Issue by SeAL80s** [erguotou520/electron-ssr#223]
## Your os

Linux Manjaro x86_64

## The version of electron-ssr

0.2.4
## What's the problem

添加订阅后，其他的节点信息会被覆盖

**Comment by erguotou520** [comment]
请详细描述问题

**Comment by SeAL80s** [comment]
添加一个订阅地址后，服务器列表里只包含当前订阅地址里所包含的节点。其他的手动添加的节点信息都没了。但是，其他的订阅地址里所包含的节点还是存在的。(偶尔其他的订阅地址里的节点也会消失，就只剩下当前添加订阅地址的信息)。在订阅管理里，添加的订阅地址是不变的。

**Comment by erguotou520** [comment]
请确认其它添加的节点的group和订阅服务器的group不一致

**Comment by SeAL80s** [comment]
@erguotou520 今天又发现一个订阅地址，服务器-订阅管理-添加订阅后，其他的节点信息，包括订阅的和手动添加的都没了，只剩下当前订阅节点的服务器信息。订阅地址没有丢失，多选订阅地址，更新后，其他的订阅节点又回来了。可是之前手动添加的服务器节点全都没了，还要手动添加。

**Comment by erguotou520** [comment]
请确认group不同

**Comment by SeAL80s** [comment]
@erguotou520 确认group不同。每个group除了自带的，都是我手动添加的。我有4-5个group，就算万一有重复的，也不应该覆盖所有的group啊。

**Comment by erguotou520** [comment]
0.2.5版本已修复
