### ISSUE TITLE
服务器订阅更新问题

### ISSUE THREAD

**Issue by sky96111** [erguotou520/electron-ssr#226]
## Your os

Manjaro Linux
## The version of electron-ssr

0.2.4
## What's the problem

服务器订阅管理键入订阅URL后订阅未被添加 ，服务器数据也不进行更新，手动导入gui-config.josn也不添加服务器。该问题同时存在于同版本的windows客户端
## App log here

未产生任何有用日志
2018-10-31 20:56:33 <info> main.js:1 () file ensured
2018-10-31 20:56:34 <info> main.js:1 (u) Register shortcut: toggleMenu, CommandOrControl+Shift+B
2018-10-31 20:57:07 <info> main.js:1 () file ensured
2018-10-31 20:57:07 <info> main.js:1 (u) Register shortcut: toggleMenu, CommandOrControl+Shift+B

**Comment by erguotou520** [comment]
应该是订阅地址问题

**Comment by sky96111** [comment]
> 应该是订阅地址问题

不因该是地址的问题吧，浏览器打开地址是可以下载base64加密的文件的，而且旧版本electronssr/c++的ssr可以订阅更新的

**Comment by erguotou520** [comment]
可能你的服务器订阅地址被墙了访问不到

**Comment by sky96111** [comment]
> 可能你的服务器订阅地址被墙了访问不到

如果被墙了的话浏览器和破娃的ssr因该也不能访问才对，但他们俩都能连接。。

**Comment by erguotou520** [comment]
请使用curl（不要使用任何代理）尝试获取订阅地址

**Comment by sky96111** [comment]
> 请使用curl（不要使用任何代理）尝试获取订阅地址

感谢提醒，终于找到问题了，是zsh把网址里的问号解释了，导致找不到地址

**Comment by sky96111** [comment]
> 请使用curl（不要使用任何代理）尝试获取订阅地址

zsh没有关闭解释这个功能，可能需要改源码让electron-ssr强制使用bash来解决

**Comment by erguotou520** [comment]
electron-ssr与zsh无关
