### ISSUE TITLE
Linux版本PAC模式代理不成功，全局模式可以

### ISSUE THREAD

**Issue by HanXiaoTeng** [erguotou520/electron-ssr#227]
OS:Manjaro Linux

 version:0.24

Linux版本PAC模式代理不成功，国内网站可以，国外网站不可以代理。全局模式可以

**Comment by HanXiaoTeng** [comment]
更换下面问题的pac文件以后 PAC模式可以代理 感觉Linux下的PAC文件有问题

**Comment by erguotou520** [comment]
请在已有的issue中说明
