### ISSUE TITLE
编辑服务器对话框是空白的

### ISSUE THREAD

**Issue by macaty** [erguotou520/electron-ssr#229]
系统：deepin
Linux marco-vpc 4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018 x86_64 GNU/Linux

版本：０．２．４

问题：
右键ＡＰＰ图标－＞＂服务器＂选项－＞＂编辑服务器＂选项　的弹出对话框中，显示空白，如图

附件一　问题截图

![snipaste_2018-11-06_10-57-29](https://user-images.githubusercontent.com/16797633/48040184-d17f2880-e1b2-11e8-962d-34b245af7425.png)

附件二　系统版本
![snipaste_2018-11-06_10-55-11](https://user-images.githubusercontent.com/16797633/48040093-7d744400-e1b2-11e8-8c7b-5b43a247761a.png)

**Comment by erguotou520** [comment]
点帮助 打开开发者工具 切到console面板 看下有没有报错

**Comment by LiJiahuiQAQ** [comment]
我的也是这样,也是deepin的系统
[log.txt](https://github.com/erguotou520/electron-ssr/files/2560226/log.txt)

**Comment by erguotou520** [comment]
请不要泄露自己的配置

**Comment by bibichuan** [comment]
我的系统也是deepin,什么都不显示
![_ _20181109165134](https://user-images.githubusercontent.com/14054904/48252500-e1f80300-e43f-11e8-98f9-a71f917f7937.png)

**Comment by bibichuan** [comment]
打开开发者帮助，按F5刷新，就可以显示界面了。同时又出现了另一个问题，就是再次打开后，以前的配置文件没有了，要重新配置才能生效

**Comment by macaty** [comment]
非常感谢.OK啦

**Comment by adaaaaaa** [comment]
@erguotou520 “订阅管理”里面添加订阅地址失败。。。
每次添加了，一更新就变成“暂无订阅服务器”。。。

**Comment by erguotou520** [comment]
请使用0.2.5版本测试

**Comment by erguotou520** [comment]
如果仍然有问题再打开issue
