### ISSUE TITLE
选项不全

### ISSUE THREAD

**Issue by edwinhuish** [erguotou520/electron-ssr#23]
协议里没有auth_chain_a选项，
加密里没有none

**Comment by erguotou520** [comment]
可以在初始化页面自行添加哦，初始化后也可以手动在配置文件中添加

**Comment by edwinhuish** [comment]
初始化页面？ 我下载的是1.0的releases, electron-ssr-0.1.0.tar.gz

没有看到初始化页面。

**Comment by edwinhuish** [comment]
另外配置文件在哪里呢？

**Comment by edwinhuish** [comment]
sorry,看到配置文件了。谢谢。

windows: C:\Users\{your username}\AppData\Local\Programs\electron-ssr
linux: ~/.config/electron-ssr
mac: ~/Library/Application Support/electron-ssr

**Comment by erguotou520** [comment]
就是`0.1.0`版本中加的功能，第一次运行时应该会看到要求选择python地址哪里

**Comment by edwinhuish** [comment]
没有要求选择python，仅有要求选择shadowsocksr/shadowsocks的目录。貌似没有其他选项。

另外，遇到跟 #22 同样的问题。修改协议后没有作用。

**Comment by erguotou520** [comment]
额，我说的选择python地址就是选择`shadowsocksr/shadowsocks`的目录，也就是`local.py`的目录，在那个页面可以添加新协议以及新method

**Comment by edwinhuish** [comment]
``` shadowsocksr/shadowsocks ``` 目录不会添加协议和method，我在你的配置文件 ``` ~/.config/electron-ssr/shadowsocksr.json ``` 里添加了。。。。

**Comment by erguotou520** [comment]
:sweat: 并不是说在`shadowsocksr/shadowsocks` 目录添加，而是那个初始化页面可以添加

**Comment by erguotou520** [comment]
我看看再截个图放readme

**Comment by edwinhuish** [comment]
谢谢，我想我知道你说的是那个页面了。。只是那个页面一般都会选择好``` shadowsocksr/shadowsocks ``` 后就会跳过，一般不会研究下面的作用。。。

另外建议你这个初始化页面理应在初始化后还能设置才对，否则一旦设置错了，就纠结了。

**Comment by erguotou520** [comment]
懒得再加页面而已 😢

**Comment by wle6** [comment]
我就是设置错了，找不到页面了，不能修改了，怎么办？

**Comment by edwinhuish** [comment]
@wle6 看下面这些位置的配置文件
```
windows: C:\Users{your username}\AppData\Local\Programs\electron-ssr
linux: ~/.config/electron-ssr
mac: ~/Library/Application Support/electron-ssr
```

**Comment by wle6** [comment]
在初始化页面选择shadowsocksr/shadowsocks的目录，是按照界面提供的网址下载的shadowsocks文件夹，进入软件后扫描二维码成功，但配合firefox不能连接，是不是还有什么步骤没做？

**Comment by edwinhuish** [comment]
貌似不是全局翻墙的吧？浏览器还需要扶墙插件。

**Comment by wle6** [comment]
都装了，连不上，我是osx系统。是不是只要初始化界面指定shadowsocks文件夹，打开软件二维码扫描后，就能用了？

**Comment by erguotou520** [comment]
是啊
