### ISSUE TITLE
托盘运行不正常

### ISSUE THREAD

**Issue by Dimerbone** [erguotou520/electron-ssr#234]
Deepin 15.8 Destop
electron-ssr 0.2.3
deepin更新至15.8后，托盘图标变为electron原子，而非小飞机，点击后没有任何反应，在Deepin15.7中是正常的

**Comment by Dimerbone** [comment]
问题已解决

**Comment by kid1412621** [comment]
https://github.com/eNkru/electron-xiami/issues/30

**Comment by kid1412621** [comment]
https://github.com/electron/electron/issues/9046
