### ISSUE TITLE
运行时ssr窗体界面消失

### ISSUE THREAD

**Issue by HarryHq** [erguotou520/electron-ssr#235]
## Your os 

* Ubuntu18.04
## The version of electron-ssr  

* electron-ssr   0.2.4
## What's the problem

* 安装是成功的，配置也成功的，但是配置好并添加后，我双击添加的IP，主窗体就消失了，而且再次运行窗体也没有出来
![image](https://user-images.githubusercontent.com/33572465/48632695-83f98b80-e9fc-11e8-82db-8cc9921dfde0.png)

**Comment by erguotou520** [comment]
请正确使用gui程序
