### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by wle6** [erguotou520/electron-ssr#24]
我在初始化界面按照提供的网站下载了shadowsocks文件夹并制定为目录，打开软件扫描二维码成功后，配合firefox还是不能连接，是什么原因？
日志：2017-7-16 10:42:44 stdout:
ERROR: server addr not specified
2017-7-16 10:42:44 stdout:
IPv6 not support
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address
  -p SERVER_PORT         server port, default: 8388
  -b LOCAL_ADDR          local binding address, default: 127.0.0.1
  -l LOCAL_PORT          local port, default: 1080
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

Online help: <https://github.com/shadowsocks/shadowsocks>

2017-7-16 10:42:56 stdout:
ERROR: server addr not specified
2017-7-16 10:42:56 stdout:
IPv6 not support
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address
  -p SERVER_PORT         server port, default: 8388
  -b LOCAL_ADDR          local binding address, default: 127.0.0.1
  -l LOCAL_PORT          local port, default: 1080
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

Online help: <https://github.com/shadowsocks/shadowsocks>

**Comment by erguotou520** [comment]
看上去是不支持ipv6的地址，换成ipv4的看看

**Comment by wle6** [comment]
应该不是节点的问题，osx系统下这个软件的操作流程是怎样的？

**Comment by erguotou520** [comment]
一样的啊 打开 完成初始化 添加服务节点 勾选运行

**Comment by erguotou520** [comment]
跟shadowsocks客户端一样的

**Comment by wle6** [comment]
初始化界面要求指定shadowsocks目录，我按照界面的网址下载了，shadowsocks目录应该放在哪里？

**Comment by erguotou520** [comment]
下载的文件你随便放哪 你只需在初始化时指定到源码的`local.py`所在的目录即可

**Comment by beesuns** [comment]
@erguotou520 Where is this local.py file?

**Comment by erguotou520** [comment]
@beesuns In `shadowsocks` folder
