### ISSUE TITLE
Ubuntu18.04，Python有安装，命令行也能正确执行，但不能代理

### ISSUE THREAD

**Issue by yanzhenjie** [erguotou520/electron-ssr#241]
应该是我哪里缺少了操作或者配置，有人知道的话麻烦告知一下。

环境：
1. 系统是Ubuntu18.04  
2. Python2.7和Python3.6都有安装

测试：
1. 从日志中复制命令加`-k 密码`，可以正确执行，但是无代理效果，从系统Setting中设置后也无效
2. 把python切换为2.7和3.6再使用electron-ssr都无效，修改系统代理后也无效（切换python版本时修改/usr/bin中软链地址，切打印版本确认过）
3. 下载ssr，通过命令行和config.json也测试过，修改了系统代理还是无效

家里的ubuntu和单位的ubuntu都是如此，应该是我自己的问题，但是之前使用electron-ssr时，安装了python2和3就可以用，虽然pac模式不可用，但是切换到全局就可以了，现在都不行了。

下面是命令执行后的结果截图和系统设置代理的截图：
![命令执行结果](https://user-images.githubusercontent.com/13534988/48975585-cf700180-f0ae-11e8-8517-6e8ba5587a57.png)

![系统代理设置](https://user-images.githubusercontent.com/13534988/48975590-07774480-f0af-11e8-8366-ebfb2de505ac.png)

系统代理这儿，开始没设置http和ftp代理，是后面测试一个个添加的。

**Comment by erguotou520** [comment]
参照`https://github.com/erguotou520/electron-ssr/blob/0.3/docs/FAQ.md` 第4条
