### ISSUE TITLE
Ubuntu18.04 浏览器翻墙成功 但命令行无法curl

### ISSUE THREAD

**Issue by xsjcTony** [erguotou520/electron-ssr#249]
使用electron ssr 0.2.4, 下载的tar文件 解压直接使用
浏览器可以正常翻墙浏览google, youtube等网站

命令行尝试 sudo curl www.google.com

已复制http代理设置, 黏贴至命令行
export http_proxy=
export https_proxy=
已完成

浏览器依然照常访问
但是命令行不行:
user@hostname:~$ sudo curl www.google.com
curl: (56) Recv failure: Connection reset by peer

请问是哪里出错了呢

**Comment by xsjcTony** [comment]
user@hostname:~$ sudo curl https://www,google.com
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443

**Comment by StevenPZChan** [comment]
> 使用electron ssr 0.2.4, 下载的tar文件 解压直接使用
> 浏览器可以正常翻墙浏览google, youtube等网站
> 
> 命令行尝试 sudo curl [www.google.com](http://www.google.com)
> 
> 已复制http代理设置, 黏贴至命令行
> export http_proxy=
> export https_proxy=
> 已完成
> 
> 浏览器依然照常访问
> 但是命令行不行:
> user@hostname:~$ sudo curl [www.google.com](http://www.google.com)
> curl: (56) Recv failure: Connection reset by peer
> 
> 请问是哪里出错了呢

不用sudo直接curl就可以，sudo的环境变量不能直接export设置

**Comment by WAAutoMaton** [comment]
curl可以使用--proxy "socks5://***"

**Comment by erguotou520** [comment]
请使用0.2.5版本测试
