### ISSUE TITLE
输入订阅地址之后 UI界面消失

### ISSUE THREAD

**Issue by pikechu** [erguotou520/electron-ssr#252]
第一次安装 首先用SSR连接添加节点没问题 输入订阅地址之后按了一下ENTER UI界面就消失了。再次打开electron-ssr没有反应 重启之后会弹出订阅更新的通知。但是找不到程序在哪也打不开。环境ubuntu 18.04。求解～

**Comment by erguotou520** [comment]
请先搜索issue
