### ISSUE TITLE
怎么安装运行呀？

### ISSUE THREAD

**Issue by ziyoo365** [erguotou520/electron-ssr#253]
可以给新手安装提示一下吗，试了好久都不能运行成功，树莓派3b+和电脑vm虚拟机ubuntu18.10都试过了，就是不会安装，npm install报错

**Comment by yi0322** [comment]
ubuntu18.10 难道不是双击直接安装了吗?  =.=

ubuntu下个deb包就直接双击安装
[下载地址](https://github.com/erguotou520/electron-ssr/releases)

**Comment by yi0322** [comment]
试试自己装ssr
https://github.com/shadowsocksr-rm/shadowsocksr
https://github.com/shadowsocksrr/shadowsocksr
