### ISSUE TITLE
更新ssr版本

### ISSUE THREAD

**Issue by bafflingbug** [erguotou520/electron-ssr#255]
## What's the problem

可否自动下载的ssr更新为最新版
由`shadowsocksr-backup/shadowsocksr#dev`更换为`shadowsocksrr/shadowsocksr#akkariiin/master`或者`shadowsocksrr/shadowsocksr#akkariiin/dev`

附上github链接：https://github.com/shadowsocksrr/shadowsocksr/tree/akkariiin/master

**Comment by erguotou520** [comment]
自行下载 然后在设置中选择本地路径即可
