### ISSUE TITLE
运行没有效果

### ISSUE THREAD

**Issue by zengcanxiang** [erguotou520/electron-ssr#26]
按照wiki里面的步骤来，下载了代码到本地，然后关联了带local.py的目录路径，然后添加了服务器，点界面的确定，系统代理也勾选了，但是感觉没有效果。网站什么的还是访问不了

**Comment by erguotou520** [comment]
贴下日志看看

**Comment by chenws1999** [comment]
我也遇到了类似情况,下载的是linux下面的压缩包
看日志的错误是:
`2017-7-20 17:22:25 stdout:
ERROR: server addr not specified
2017-7-20 17:22:25 stdout:
IPv6 support
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address
  -p SERVER_PORT         server port, default: 8388
  -b LOCAL_ADDR          local binding address, default: 127.0.0.1
  -l LOCAL_PORT          local port, default: 1080
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

Online help: <https://github.com/shadowsocks/shadowsocks>

2017-7-20 17:22:25 stdout:
2017-07-20 17:22:25 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2017-7-20 17:22:25 stdout:
2017-07-20 17:22:25 ERROR    shell.py:50 [Errno 13] Permission denied: '/var/run/shadowsocksr.pid'
2017-7-20 17:22:25 stdout:
IPv6 support
IPv6 support
2017-7-20 17:22:29 stdout:
ERROR: server addr not specified
2017-7-20 17:22:29 stdout:
IPv6 support
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address
  -p SERVER_PORT         server port, default: 8388
  -b LOCAL_ADDR          local binding address, default: 127.0.0.1
  -l LOCAL_PORT          local port, default: 1080
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

Online help: <https://github.com/shadowsocks/shadowsocks>

2017-7-20 17:22:29 stdout:
2017-07-20 17:22:29 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2017-7-20 17:22:29 stdout:
2017-07-20 17:22:29 ERROR    shell.py:50 [Errno 13] Permission denied: '/var/run/shadowsocksr.pid'
2017-7-20 17:22:29 stdout:
IPv6 support
IPv6 support`

**Comment by chenws1999** [comment]
把仓库中的源代码翻了翻也看不出个所以然,直接运行python脚本是可以成功运行的.

**Comment by erguotou520** [comment]
看上去是没有配置服务器地址？

**Comment by chenws1999** [comment]
这个我看您的源码感觉没没问题啊.. 还有一种可能性是 -d start这种模式启动因为权限问题出错

**Comment by chenws1999** [comment]
我在直接用Python运行local.py脚本的测试中,发现必须是root用户下才能成功运行

**Comment by wle6** [comment]
我也遇到同样的问题，osx该怎样运行？

**Comment by zengcanxiang** [comment]
@erguotou520 我的日志和上面的仁兄是差不多的,也是有这个
```java
2017-7-21 9:15:7 stdout:
2017-07-21 09:15:07 INFO     util.py:85 loading libsodium from libsodium.so.18
2017-7-21 9:15:7 stdout:
2017-07-21 09:15:07 ERROR    shell.py:50 [Errno 13] Permission denied: '/var/run/shadowsocksr.pid'
2017-7-21 9:15:7 stdout:
IPv6 support
IPv6 support
```
我的服务器地址配置的是类似 `us1.ssnice.club` 这样的，不是IP。
暂时还没试过在终端运行local.py，现在去试下

**Comment by erguotou520** [comment]
看上去是要用root权限才能运行

**Comment by zengcanxiang** [comment]
![qq 20170721094811](https://user-images.githubusercontent.com/16033497/28445877-bd65ad20-6df9-11e7-9f7e-f4e1679c9698.png)
通过配置文件sudo运行也不行

**Comment by zengcanxiang** [comment]
之前用shadowsocks-qt5可以，但是SS不行了，要求用SSR客户端，顿时就gg了

**Comment by erguotou520** [comment]
这个是重复启动导致的，你停掉原来客户端再用命令行尝试

**Comment by zengcanxiang** [comment]
我也看到了，然后都停掉之后，就抱这个了
![_ _20170721100252](https://user-images.githubusercontent.com/16033497/28446199-c9bc92a8-6dfb-11e7-8541-4444f3dfda8a.png)

**Comment by erguotou520** [comment]
这个没报错啊

**Comment by zengcanxiang** [comment]
.... 我之前把浏览器的proxy switchOmega 插件给停了，一直打不开网站.....
