### ISSUE TITLE
Windows10 配置文件目录错误

### ISSUE THREAD

**Issue by Javi2004** [erguotou520/electron-ssr#265]
## Your os

Windows 10 专业版 1803

## The version of electron-ssr

0.2.5

## What's the problem

在Readme.md中，Windows的Gui-config.json位置是：C:\Users\{your username}\AppData\Local\Programs\electron-ssr\gui-config.json
但是在我的系统中是"C:\Users\Admin\AppData\Roaming\electron-ssr\gui-config.json"

显然不大正常

**Comment by erguotou520** [comment]
抱歉，那是之前版本的路径位置，一会修改
