### ISSUE TITLE
Deepin Linux 点击图标出来一个黑窗

### ISSUE THREAD

**Issue by BackTrackCRoot** [erguotou520/electron-ssr#271]
使用Deepin Linux系统，直接在启动器中打开electorn-ssr 会弹出终端，关掉终端程序会退出。效果如下：
![_ _20190109094322](https://user-images.githubusercontent.com/4964761/50870440-0e55de80-13f3-11e9-83dc-bcb1a3a6be66.png)
很迷，不知道怎么才能消掉这个。

**Comment by erguotou520** [comment]
#262
