### ISSUE TITLE
Ubuntu+FireFox+飞机图标==不能FQ

### ISSUE THREAD

**Issue by AndrewGong2016** [erguotou520/electron-ssr#274]
## Your os
Ubuntu16.04 LTS

## The version of electron-ssr
0.2.5

## What's the problem
Ubuntu+FireFox+飞机图标==不能FQ

## App log here
CMD 执行 electron 的log：
2019-01-13 15:57:10:785 [info] Register shortcut: toggleWindow, Ctrl+Shift+W
2019-01-13 15:57:10:882 [info] run command: python /home/andrew/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s IP -p 4389 -k ****** -m XXX -O XXX -o plain -b XXX -l 1080
2019-01-13 15:57:10:918 [info] pac server listen at: 127.0.0.1:2333
2019-01-13 15:57:10:923 [info] http proxy server listen at: 127.0.0.1:12333
2019-01-13 15:57:11:517 [error] 2019-01-13 15:57:11 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2019-01-13 15:57:11 INFO     local.py:50 local start with protocol[auth_sha1_v4] password [password] method [method] obfs [obfs [] obfs_param []
2019-01-13 15:57:11 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-01-13 15:57:11 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

**Comment by AndrewGong2016** [comment]
请诸位大侠们帮忙 分析一下，感谢

**Comment by AndrewGong2016** [comment]
> ## Your os
> 
> Ubuntu16.04 LTS
> ## The version of electron-ssr
> 
> 0.2.5
> ## What's the problem
> 
> Ubuntu+FireFox+飞机图标==不能FQ
> ## App log here
> 
> CMD 执行 electron 的log：
> 2019-01-13 15:57:10:785 [info] Register shortcut: toggleWindow, Ctrl+Shift+W
> 2019-01-13 15:57:10:882 [info] run command: python /home/andrew/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s IP -p 4389 -k ****** -m XXX -O XXX -o plain -b XXX -l 1080
> 2019-01-13 15:57:10:918 [info] pac server listen at: 127.0.0.1:2333
> 2019-01-13 15:57:10:923 [info] http proxy server listen at: 127.0.0.1:12333
> 2019-01-13 15:57:11:517 [error] 2019-01-13 15:57:11 INFO util.py:85 loading libcrypto from libcrypto.so.1.0.0
> 2019-01-13 15:57:11 INFO local.py:50 local start with protocol[auth_sha1_v4] password [password] method [method] obfs [obfs [] obfs_param []
> 2019-01-13 15:57:11 INFO local.py:54 starting local at 127.0.0.1:1080
> 2019-01-13 15:57:11 INFO asyncdns.py:324 dns server: [('127.0.1.1', 53)]

**Comment by erguotou520** [comment]
请先使用命令行代理试下，firefox的代理不一定走socks

**Comment by AndrewGong2016** [comment]
请问 ，命令行的代理配置如何配置呢？SSr在windows上配置firefox代理可以正常FQ，现在需要在Ubuntu上也能work；或者推荐一个在Ubuntu上的浏览器

**Comment by AndrewGong2016** [comment]
Ubuntu上使用的Firefox 配置了手动设置代理+sockv5，想确认一下Ubuntu系统网络里还需要配置代理吗

**Comment by AndrewGong2016** [comment]
`andrew@andrew-virtual-machine:~$ curl https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
`

curl https://google.com 结果如上

**Comment by AndrewGong2016** [comment]
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>

**Comment by AndrewGong2016** [comment]
curl https://google.com
成功获取到内容
HTML.............
XXXX
HTML.............

**Comment by AndrewGong2016** [comment]
使用谷歌浏览器 并在ubuntu系统代理里配置手动代理127.0.0.1::1080 成功FQ~~~done and thanks!
