### ISSUE TITLE
软件无法工作

### ISSUE THREAD

**Issue by WAAutoMaton** [erguotou520/electron-ssr#28]
启动软件并正确配置服务器信息后发现无法代理，查看日志文件之后发现错误：
2017-07-22 11:13:05 ERROR    shell.py:50 [Errno 13] Permission denied: '/var/run/shadowsocksr.pid'
请问如何解决？

ssr版本：3.3.3
electron-ssr版本：0.1.0
系统：Ubuntu 16.04 LTS

**Comment by WAAutoMaton** [comment]
现在怀疑是没有sudo导致的，但是如果使用sudo运行程序的话任务栏就无法显示小图标了，状况和[issue #17](https://github.com/erguotou520/electron-ssr/issues/17)类似

**Comment by erguotou520** [comment]
@breakwa11 帮忙看下？

**Comment by breakwa11** [comment]
这我也不知道，看看那个路径的权限吧，如果没权限就chmod就好了

**Comment by WAAutoMaton** [comment]
@erguotou520 直接运行python版ssr时发现必须要sudo才能运行，但是使用sudo运行electron-ssr时就无法在任务栏显示出软件的图标

**Comment by BevisGoh** [comment]
2017-7-24 0:9:37 stdout:
2017-07-24 00:09:37 INFO     util.py:85 loading libsodium from libsodium.so.18
2017-07-24 00:09:37 ERROR    shell.py:50 [Errno 13] Permission denied: '/var/run/shadowsocksr.pid'
2017-7-24 0:9:37 stdout:
IPv6 support
IPv6 support

好像是缺少权限，该怎么做？

**Comment by chenws1999** [comment]
@WAAutoMaton 我这里也是这个问题...

**Comment by erguotou520** [comment]
@sudo权限运行吧

**Comment by WAAutoMaton** [comment]
@erguotou520 现在的问题就是sudo运行时任务栏不出图标了（代理好像也没法工作）

**Comment by erguotou520** [comment]
嗯，近期调试下

**Comment by erguotou520** [comment]
测试了下，linux下如果需要以`-d`模式运行的话需要`root`权限，而`pid`权限问题在`shadowsocksr`的项目中也有类似的issue，所以下个版本中修改为非`-d`模式运行。
@WAAutoMaton @lixiaodongsql  @wudimenghuan @edwinhuish
欢迎大家测试新版

**Comment by erguotou520** [comment]
`0.1.1`已发布

**Comment by WAAutoMaton** [comment]
@erguotou520 更新0.1.1之后发现依旧无法连上代理
![image](https://user-images.githubusercontent.com/24771667/28743218-fd3aaed0-7409-11e7-82ba-231cf40777fd.png)
观察软件给出的命令发现没有传递obfs_param和timeout,但我已经配置了这两个参数.望修复

**Comment by wle6** [comment]
同样的情况，请修复！

**Comment by erguotou520** [comment]
python命令行里没看到这2个参数

**Comment by erguotou520** [comment]
@WAAutoMaton @wle6 `obfs_param`参数已修复，但`timeout`参数并没有在wiki中见到？

**Comment by erguotou520** [comment]
请在新的版本中验证该问题，谢谢

**Comment by erguotou520** [comment]
先关了，如果有什么后续问题再开
