### ISSUE TITLE
electron-ssr can't run in Ubuntu 17.04.

### ISSUE THREAD

**Issue by lixiaodongsql** [erguotou520/electron-ssr#29]
Thank you very much for developing Linux version SSR. I really appreciate it. I used alien to install RPM package on Ubuntu 17.04. At first electron-ssr can run. Should I use the confirm button to scan the QR code? After I used the confirm button to scan a QR code and click the confirm button, the electron-ssr icon only can appear in the menu for a while. After a while the electron-ssr icon disappears. Currently after I start the electron-ssr, the electron-ssr icon only can appear in the menu for a while. After a while the electron-ssr icon disappears. Thank you so much for your help. I really appreciate it.

**Comment by erguotou520** [comment]
咋们还是说中文吧。这个问题正在排查中，很多人都提到Ubuntu上有这个问题

**Comment by erguotou520** [comment]
请在新版0.1.1中验证

**Comment by erguotou520** [comment]
请在新版0.2.0中验证

**Comment by erguotou520** [comment]
因长期不回复而关闭issue，如果确认还有该问题请重新打开
