### ISSUE TITLE
分组内服务器太多超出屏幕显示范围且无法滚动

### ISSUE THREAD

**Issue by haoyet** [erguotou520/electron-ssr#291]
## Your os
Arch linux
## The version of electron-ssr
0.2.6
## What's the problem
一个组里的服务器太多会超出屏幕显示范围并且无法向下滚动

**Comment by zuikme** [comment]
me too

**Comment by hoshinohikari** [comment]
Manjaro-kde +1

**Comment by erguotou520** [comment]
大致提供下截图，记得打码

**Comment by haoyet** [comment]
> 大致提供下截图，记得打码

我刚刚试了下又没问题了，可能是后续更新修复了。
但是在这之间我曾重装并更换过桌面环境（DDE-->KDE）所以不知道有没有关系。

之前的问题就是在以下界面的时候（右键任务栏图标->服务器-->某个分组）如果组内服务器太多会无法上下滚动，出问题的时候鼠标滚轮和点击上面的箭头都没用。
![图片](https://user-images.githubusercontent.com/28365438/54938761-6afa6d00-4efd-11e9-8913-732bca40550c.png)

总之现在问题是修复了，感谢您做的这么漂亮的客户端w

**Comment by erguotou520** [comment]
这种任务栏的不能滚动应该只能是系统级别的了，这个我没法控制

**Comment by haoyet** [comment]
如果是系統級的話那很有可能是桌面環境的原因？

不知上面兩位有同樣問題的同志是什麼桌面環境呢？
