### ISSUE TITLE
electron-ssr can't start in Fedora 25

### ISSUE THREAD

**Issue by lixiaodongsql** [erguotou520/electron-ssr#30]
After I installed the RPM package on Fedora 25, I clicked the ShadowsocksR icon in Applications. But electron-ssr can't start. Thank you so much for your help again.

**Comment by erguotou520** [comment]
linux系统都有这样的问题，你可以先试下未发布的0.1.1版本

**Comment by lixiaodongsql** [comment]
Thank you very much for your help. I can't find the download URL of electron-ssr 0.1.1

**Comment by erguotou520** [comment]
嗯，目前处于Draft状态，等待mac版测试完成后就正式release

**Comment by erguotou520** [comment]
已发布
