### ISSUE TITLE
端口被占用

### ISSUE THREAD

**Issue by TsaiHao** [erguotou520/electron-ssr#303]
##  OS

CentOS 7
## The version of electron-ssr

0.2.6
## What's the problem

每次启动程序都提示1080端口被占用。翻墙也无效。日志显示Address already in use，换端口也不行
## App log here

Address already in use

**Comment by erguotou520** [comment]
发完整日志

**Comment by TsaiHao** [comment]
你好已经解决了

**Comment by Lynss** [comment]
请问如何解决的呢,碰到类似问题
