### ISSUE TITLE
菜鸡求助，Ubuntu 18.04内建http代理正常，G无法访问[未完全解决]

### ISSUE THREAD

**Issue by lucky-znk** [erguotou520/electron-ssr#317]
## Your os
Ubuntu 18.04

## The version of electron-ssr
v0.26 deb包安装

## What's the problem
应用可以正常启动，服务器正常（手机测试可访问），Terminal内export了http代理后curl可以访问google/fb/tw..etc.但无论FF还是Chrome都无法访问。已尝试：
1.系统代理模式-不启用，FF手动设置HTTP代理127.0.0.1:1080，其他协议同HTTP，无法访问G和Baidu
2.系统代理模式-全局，FF使用系统代理，仍无法访问G和Baidu
3.系统代理模式-全局，Chrome默认使用系统代理，无法访问G，但是能访问Baidu，很微妙
系统全局代理时telnet 127.0.0.1 1080测试端口可以连接，关闭全局代理再telnet就失败了，FF载入网页也会秒失败，从而可以确定端口没有冲突，Terminal内导出http代理设置也没问题，但为何Chrome和FF设置代理就无法访问？如果代理失败FF任何网站都无法访问还可以理解，但Chrome只有需要翻的无法访问，国内站点一切正常，看起来也没走代理？求教

## App log here
看起来没什么问题的log，本以为是openssl1.1.0的EVP_CIPHER_CTX_cleanup()问题，后来也替换成EVP_CIPHER_CTX_reset()了，问题依旧存在
2019-03-07 15:49:04:938 [info] run command: python /home/{username}/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s {server_ip} -p {server_port} -k ****** -m aes-256-cfb -O auth_sha1_v4 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-03-07 15:49:05:036 [error] 2019-03-07 15:49:05 INFO     util.py:85 loading libcrypto from libcrypto.so.1.1
2019-03-07 15:49:05:037 [error] 2019-03-07 15:49:05 INFO     local.py:50 local start with protocol[auth_sha1_v4] password [hhUeJoFf] method [aes-256-cfb] obfs [tls1.2_ticket_auth] obfs_param []
2019-03-07 15:49:05 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-03-07 15:49:05 INFO     asyncdns.py:324 dns server: [('127.0.0.53', 53)]
2019-03-07 15:50:24:321 [info] http proxy server listen at: 127.0.0.1:12333

**Comment by erguotou520** [comment]
运行并没有报错，而且按照你之前的测试应该也是通的，所以比较诡异，建议多测试

**Comment by lucky-znk** [comment]
> 运行并没有报错，而且按照你之前的测试应该也是通的，所以比较诡异，建议多测试

这个诡异的问题我已经无解了，只有系统PAC代理，FF使用系统代理可访问G、FB等，Chrome无论如何都无法访问，系统设置里可以看到代理模式为自动，指向http://127.0.0.1:2333/proxy.pac，此PAC也可正常访问。再切回系统全局代理，就又变成上述2、3，凡是要翻的都访问不了了……我只是想开全局给Chrome装个ProxySwitchy Omega只给浏览器走代理，不过现在看来系统无代理只给FF配代理也无效，即便Chrome装好插件应该也是无法访问的……不知所措.jpg

**Comment by erguotou520** [comment]
我这边没办法记录这些日志。你用chrome的omega试试？我一般都是用omega的

**Comment by lucky-znk** [comment]
> 我这边没办法记录这些日志。你用chrome的omega试试？我一般都是用omega的

我试了下，关闭系统代理，命令行google-chrome --proxy-server="socks5://localhost:1080"可以开启Chrome全局走代理，安装好Proxy SwitchyOmega后添加规则和FF一个效果。只有系统PAC，FF走系统代理和系统不代理，Chrome命令行设置代理可以使用，其他情况FF和Chrome均无法使用……有点理解不能。而且看不到连接的详细log，无法得知浏览器Loading时酸酸乳是否在向服务器发送请求

**Comment by lucky-znk** [comment]
> 我这边没办法记录这些日志。你用chrome的omega试试？我一般都是用omega的

发现只有PAC能用，而且系统PAC只有FF使用系统代理有效，Chrome+Proxy SwitchyOmega自动切换或走系统代理均无效，但系统代理关闭，在PSO里单独建立PAC Profile指向pac文件可生效。感觉还是酸酸乳自身代理的问题，现在只能这样用了

**Comment by codeAndxv** [comment]
相同ubuntu18，遇到类似问题

**Comment by matyhtf** [comment]
https://github.com/erguotou520/electron-ssr/issues/316

相同问题。因为没安装python

**Comment by lucky-znk** [comment]
> #316
> 
> 相同问题。因为没安装python

然而我系统里有python2.7和3.6，而且也在/usr/bin下分别替换过python的symlink为2.7和3.6试过，都不生效，只能用PAC

**Comment by lanybass** [comment]
同，只能pac，全局就断网

**Comment by konwww** [comment]
那我怎么pac都用不了？服务器是没有问题的，但是报错就是
2019-04-09 17:06:48:074 [error] 2019-04-09 17:06:48 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-04-09 17:06:48 ERROR    tcprelay.py:1037 remote error, when connect to adservice.google.com:443

2019-04-09 17:06:48:991 [error] 2019-04-09 17:06:48 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-04-09 17:06:48 ERROR    tcprelay.py:1037 remote error, when connect to adservice.google.com:443

2019-04-09 17:07:18:683 [error] 2019-04-09 17:07:18 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-04-09 17:07:18 ERROR    tcprelay.py:1037 remote error, when connect to adservice.google.com:443

**Comment by erguotou520** [comment]
python-ssr的报错

**Comment by ylroki** [comment]
> ## Your os
> 
> Ubuntu 18.04
> ## The version of electron-ssr
> 
> v0.26 deb包安装
> ## What's the problem
> 
> 应用可以正常启动，服务器正常（手机测试可访问），Terminal内export了http代理后curl可以访问google/fb/tw..etc.但无论FF还是Chrome都无法访问。已尝试：
> 1.系统代理模式-不启用，FF手动设置HTTP代理127.0.0.1:1080，其他协议同HTTP，无法访问G和Baidu
> 2.系统代理模式-全局，FF使用系统代理，仍无法访问G和Baidu
> 3.系统代理模式-全局，Chrome默认使用系统代理，无法访问G，但是能访问Baidu，很微妙
> 系统全局代理时telnet 127.0.0.1 1080测试端口可以连接，关闭全局代理再telnet就失败了，FF载入网页也会秒失败，从而可以确定端口没有冲突，Terminal内导出http代理设置也没问题，但为何Chrome和FF设置代理就无法访问？如果代理失败FF任何网站都无法访问还可以理解，但Chrome只有需要翻的无法访问，国内站点一切正常，看起来也没走代理？求教
> ## App log here
> 
> 看起来没什么问题的log，本以为是openssl1.1.0的EVP_CIPHER_CTX_cleanup()问题，后来也替换成EVP_CIPHER_CTX_reset()了，问题依旧存在
> 2019-03-07 15:49:04:938 [info] run command: python /home/{username}/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s {server_ip} -p {server_port} -k ****** -m aes-256-cfb -O auth_sha1_v4 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
> 2019-03-07 15:49:05:036 [error] 2019-03-07 15:49:05 INFO util.py:85 loading libcrypto from libcrypto.so.1.1
> 2019-03-07 15:49:05:037 [error] 2019-03-07 15:49:05 INFO local.py:50 local start with protocol[auth_sha1_v4] password [hhUeJoFf] method [aes-256-cfb] obfs [tls1.2_ticket_auth] obfs_param []
> 2019-03-07 15:49:05 INFO local.py:54 starting local at 127.0.0.1:1080
> 2019-03-07 15:49:05 INFO asyncdns.py:324 dns server: [('127.0.0.53', 53)]
> 2019-03-07 15:50:24:321 [info] http proxy server listen at: 127.0.0.1:12333

和你同样的现象，mark一下，研究下

**Comment by lucky-znk** [comment]
> > ## Your os
> > Ubuntu 18.04
> > ## The version of electron-ssr
> > v0.26 deb包安装
> > ## What's the problem
> > 应用可以正常启动，服务器正常（手机测试可访问），Terminal内export了http代理后curl可以访问google/fb/tw..etc.但无论FF还是Chrome都无法访问。已尝试：
> > 1.系统代理模式-不启用，FF手动设置HTTP代理127.0.0.1:1080，其他协议同HTTP，无法访问G和Baidu
> > 2.系统代理模式-全局，FF使用系统代理，仍无法访问G和Baidu
> > 3.系统代理模式-全局，Chrome默认使用系统代理，无法访问G，但是能访问Baidu，很微妙
> > 系统全局代理时telnet 127.0.0.1 1080测试端口可以连接，关闭全局代理再telnet就失败了，FF载入网页也会秒失败，从而可以确定端口没有冲突，Terminal内导出http代理设置也没问题，但为何Chrome和FF设置代理就无法访问？如果代理失败FF任何网站都无法访问还可以理解，但Chrome只有需要翻的无法访问，国内站点一切正常，看起来也没走代理？求教
> > ## App log here
> > 看起来没什么问题的log，本以为是openssl1.1.0的EVP_CIPHER_CTX_cleanup()问题，后来也替换成EVP_CIPHER_CTX_reset()了，问题依旧存在
> > 2019-03-07 15:49:04:938 [info] run command: python /home/{username}/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s {server_ip} -p {server_port} -k ****** -m aes-256-cfb -O auth_sha1_v4 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
> > 2019-03-07 15:49:05:036 [error] 2019-03-07 15:49:05 INFO util.py:85 loading libcrypto from libcrypto.so.1.1
> > 2019-03-07 15:49:05:037 [error] 2019-03-07 15:49:05 INFO local.py:50 local start with protocol[auth_sha1_v4] password [hhUeJoFf] method [aes-256-cfb] obfs [tls1.2_ticket_auth] obfs_param []
> > 2019-03-07 15:49:05 INFO local.py:54 starting local at 127.0.0.1:1080
> > 2019-03-07 15:49:05 INFO asyncdns.py:324 dns server: [('127.0.0.53', 53)]
> > 2019-03-07 15:50:24:321 [info] http proxy server listen at: 127.0.0.1:12333
> 
> 和你同样的现象，mark一下，研究下

很是尴尬，我之前机器系统盘SSD有问题，换了一块之后重新做了次18.04，现在又好了，用ProxyOmega可以正常代理了，FF也可以直接走酸酸乳代理不需要全局PAC了，偶发性BUG？
