### ISSUE TITLE
仅能代理10s

### ISSUE THREAD

**Issue by KomachiZ** [erguotou520/electron-ssr#325]
macOS Mojave,在开机时直接使用，能正常使用，十秒后刷新就显示代理服务器出问题，后来无论怎么换节点也不行，重启后还是十秒内能代理

**Comment by KomachiZ** [comment]
如果开全局模式，没有1080端口对进程，开pac模式如下图


![189C275F-FE91-4970-AFB5-173C56B994A6](https://user-images.githubusercontent.com/32158594/54478257-16932580-484b-11e9-9fdc-ff92bfcad826.png)

**Comment by erguotou520** [comment]
看下日志是否提示 connect reset by peer
