### ISSUE TITLE
manjaro-i3wm 翻不了

### ISSUE THREAD

**Issue by NeutronT** [erguotou520/electron-ssr#327]
manjaro i3桌面 无论是使用pacman版本还是用AppImage版本都翻不了。
全局代理模式下ping谷歌如下：
ping -c 4 www.google.com 
PING www.google.com(hkg07s22-in-x04.1e100.net (2404:6800:4005:803::2004)) 56 data bytes
--- www.google.com ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 31ms

**Comment by erguotou520** [comment]
请参考faq
