### ISSUE TITLE
debian 下无法代理 https 网站，但是可以代理 http网站

### ISSUE THREAD

**Issue by alioox** [erguotou520/electron-ssr#336]
## Your os

debian 10
## The version of electron-ssr

0.2.6
## App log here

2019-03-25 21:58:02 ERROR    tcprelay.py:971 remote error, when connect to www.bing.com:443

2019-03-25 22:05:35:175 [error] 2019-03-25 22:05:35 ERROR    tcprelay.py:969 [Errno 32] Broken pipe

> 访问 http://ip138.com (这个是不加密的)

> 您的IP是：[58.152.X.X] 来自：香港特别行政区，

确定是走代理访问的

浏览器配置全部使用代理，找了几个国外和国内的不加密的网站，都可以访问，但是加密网站都无法访问

更新：通过http 代理访问国内http网站都会报连接错误

**Comment by alioox** [comment]
在debian 9 和 debian 10 都是这样的，在最新版的centos 7 上就没有这个问题

**Comment by alioox** [comment]
在debian 9 和 debian 10 都是这样的，在最新版的centos 7 上就没有这个问题

**Comment by alioox** [comment]
我之前使用的是debian9 + appimage，无法访问，后来将系统升级到debian 10, 仍然不行，然后换 deb 包版本，仍然不行，仔细研究发现可以代理http网站，无法代理https网站。也许是我的系统的哪里有问题

**Comment by alioox** [comment]
electron-ssr 版本 2.6

**Comment by alioox** [comment]
我之前使用的是centos 7 + appimage 2.6 版本，正常使用，后来换debian9 + appimage，无法访问，后来将系统升级到debian 10, 仍然不行，然后换 deb 包版本，仍然不行，仔细研究发现可以代理http网站，无法代理https网站。也许是我的系统的哪里有问题
electron-ssr 版本 2.6

**Comment by CanvaChen** [comment]
@alioox https也转到http代理访问即可

**Comment by alioox** [comment]
> @alioox https也转到http代理访问即可

我在终端测试的时候就是使用的http代理，不行的

**Comment by alioox** [comment]
解决了，我不知道在哪里下载的 shadowsocksr，版本是 3.1.2 版本的，我重新下了一个 3.2.2 版本的就解决了
