### ISSUE TITLE
无法成功自动下载ssr

### ISSUE THREAD

**Issue by FloatingRain** [erguotou520/electron-ssr#344]
## Your os
Manjaro Linux (Kernel 5.0)

## The version of electron-ssr
0.2.6

## What's the problem
无法成功自动下载ssr，监控网络流量为0,目测是下载源地址挂了？同时ssr的源版本又存在python数组溢出错误，真是让人焦头烂额

## App log here
2019-03-30 05:47:06:022 [error] ssr download error
这一句就够了，别的没用

**Comment by erguotou520** [comment]
可以直接下载任意python ssr项目，然后手动指向该目录
