### ISSUE TITLE
Ubuntu 18.04.1 LTS下安装0.2.6. deb成功，双击后闪退

### ISSUE THREAD

**Issue by gneowing** [erguotou520/electron-ssr#352]
## Your os
Ubuntu 18.04.1 LTS

## The version of electron-ssr 
electron-ssr-0.2.6

## What's the problem
双击后闪退

## App log here
没有

**Comment by gneowing** [comment]
其实是正常的,老眼昏花没有看到其实已经正常运行了,很好用很强大,感谢作者, admiring

**Comment by rylanlee** [comment]
你好，能请教一下在Ubuntu上是怎么设置使用的吗？
