### ISSUE TITLE
MacOS High Sierra 谷歌连上几秒就连不上了

### ISSUE THREAD

**Issue by KunMinX** [erguotou520/electron-ssr#358]
## Your os

MacOS
## The version of electron-ssr

0.2.6
## What's the problem

macos优胜美地系统，谷歌访问几秒就不再能访问了，同样的账号，在windows上，是可以的。

**Comment by erguotou520** [comment]
看报错日志

**Comment by KunMinX** [comment]
@erguotou520 已卸载了 换了另一个牌子的客户端就好了
