### ISSUE TITLE
加密方式有问题

### ISSUE THREAD

**Issue by wle6** [erguotou520/electron-ssr#36]
osx系统，当节点使用chacha20、chacha20-ietf方式加密时，代理服务器无法连接，改成aes-256-cfb后一切正常，不知道为什么？希望能修复！日志显示：stderr:
/bin/sh: -c: line 0: syntax error near unexpected token `)'
/bin/sh: -c: line 0: `python /Applications/shadowsocksr-manyuser/shadowsocks/

**Comment by erguotou520** [comment]
应该是ssr的问题
