### ISSUE TITLE
大佬们帮帮忙 Ubuntu 18.04

### ISSUE THREAD

**Issue by liuchong1995** [erguotou520/electron-ssr#362]
- 04-17 16:02:35:711 [info] run command: python /home/lc/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s ********* -p ******* -k ****** -m aes-256-cfb -O auth_aes128_md5 -o plain -b 127.0.0.1 -l 1080
- 2019-04-17 16:02:35:717 [info] pac server listen at: 127.0.0.1:2333
- 2019-04-17 16:02:35:718 [info] http proxy server listen at: 127.0.0.1:12333
- 2019-04-17 16:02:35:844 [error] 2019-04-17 16:02:35 INFO     util.py:85 loading libcrypto from libcrypto.so.1.1
- 
- 2019-04-17 16:02:35:844 [error] 2019-04-17 16:02:35 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [b'147789'] method [aes-256-cfb] obfs [plain] obfs_param []
- 2019-04-17 16:02:35 INFO     local.py:54 starting local at 127.0.0.1:1080
- 2019-04-17 16:02:35 INFO     asyncdns.py:324 dns server: [('127.0.0.53', 53)]

**Comment by yoheRabit** [comment]
看这个https://github.com/erguotou520/electron-ssr/issues/230

**Comment by liuchong1995** [comment]
> 看这个#230

试了那个方法，还是上不了网，日志里面两个error是什么意思？

**Comment by erguotou520** [comment]
并没有错误，根据faq里说明的检测是否成功代理

**Comment by liuchong1995** [comment]
> 并没有错误，根据faq里说明的检测是否成功代理

我把通用设置里面的http代理取消就可以用了。
