### ISSUE TITLE
暂时停止项目的维护，直到ssr恢复源码

### ISSUE THREAD

**Issue by erguotou520** [erguotou520/electron-ssr#37]

**Comment by lipeng1a** [comment]
能不能麻烦制作一个白疵式的安装教程，我刚装上ubuntu 17.04，现在不太会装软件

**Comment by erguotou520** [comment]
下载`.tar.gz`包，解压，运行，细节请自行百度学习，这里不做细节介绍

**Comment by lipeng1a** [comment]
之前解压以后直接打开electron-ssr，第一次是有反应的，但是没有小图标，后来打开就直接没反应。然后我又下了rpm包转成deb安装，后来在系统搜索可以找到shadowsocksR，但是打不开，进程里面却已经存在

**Comment by lipeng1a** [comment]
安装以后不能运行

**Comment by lipeng1a** [comment]
现在能打开，但是桌面上没有小飞机显示

**Comment by erguotou520** [comment]
暂停项目维护，等后续进展

**Comment by lipeng1a** [comment]
现在有人接手SSR，改为SSRR

**Comment by candy2107** [comment]
https://github.com/shadowsocksrr/shadowsocksr

**Comment by WAAutoMaton** [comment]
ssr现在停更了，那是否可以考虑加入对原版ss客户端的支持？

**Comment by erguotou520** [comment]
ss的跨平台客户端不是有了么

**Comment by goudiao** [comment]
SSR并没有停更，而是改为 SSRR ，https://github.com/shadowsocksrr/shadowsocksr

**Comment by erguotou520** [comment]
大兄弟，人家那是backup

**Comment by HougeLangley** [comment]
个人觉得不像是备份，看下其他的 b 下，comment 还是有进度的。

**Comment by erguotou520** [comment]
我看了下 最近都是破娃酱在commit 我先问下 了解下情况

**Comment by HougeLangley** [comment]
妥妥的。

**Comment by erguotou520** [comment]
@breakwa11 是重新开工了么 😆

**Comment by chumuye** [comment]
哪里可以下载最新版的SSR安卓和PC版？

**Comment by goudiao** [comment]
@erguotou520 新的 SSRR 所有 comment 由原作者提交

**Comment by erguotou520** [comment]
@goudiao 哪个repo?

**Comment by erguotou520** [comment]
项目已在开发0.2.0版本，关闭通知
