### ISSUE TITLE
协议／混淆方式为空仍能进主界面

### ISSUE THREAD

**Issue by peter17ji** [erguotou520/electron-ssr#40]
主界面没有回到设置协议／混淆方式界面的按钮，于是不设置这两个的话就只能重装程序再设置

**Comment by erguotou520** [comment]
可以改配置文件啊直接

**Comment by peter17ji** [comment]
能说一下配置文件的位置吗？

**Comment by erguotou520** [comment]
https://github.com/erguotou520/electron-ssr#配置文件和日志的目录
