### ISSUE TITLE
配置正确，日志貌似也没有报错，但是还是连接不上

### ISSUE THREAD

**Issue by ATFieldBeast** [erguotou520/electron-ssr#42]
2017-09-16 23:29:24 INFO     util.py:85 loading libsodium from libsodium.so.18
2017-9-16 23:29:24 stderr:
2017-09-16 23:29:24 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [SaeqFYJR] method [chacha20-ietf] obfs [tls1.2_ticket_auth] obfs_param []
2017-09-16 23:29:24 INFO     local.py:54 starting local at 127.0.0.1:1080
2017-09-16 23:29:24 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

才用Linux的弱鸡不知道怎么回事了。。。

**Comment by ATFieldBeast** [comment]
开机报错了55555
A JavaScript error occurred in the main process

Uncaught Exception:
Error: net::ERR_INTERNET_DISCONNECTED

**Comment by erguotou520** [comment]
请先使用命令行试试

**Comment by baorongquan** [comment]
libsodium.so 感觉是这个库的问题，我的博客有介绍，你可以看下
 https://baorongquan.github.io/2017/09/09/linux-ssr-use/

**Comment by chiyeung524** [comment]
我想问一下你的情况解决了吗？？我的情况跟你一模一样…

**Comment by jklzrj168** [comment]
我的是ubuntu 16.可以链接 就是服务器编辑界面出不来了.  搜索“Linux Mint ShadowSockR
的方案”  一步步下来链接应该没有问题。

**Comment by erguotou520** [comment]
我本来只是自己兴趣做的项目，没想到你们都有人专门写博客来介绍怎么使用了 😆

**Comment by chiyeung524** [comment]
很好用啊，方便我们这些小萌新~

**Comment by chiyeung524** [comment]
就是centos7好像不能全局~因此需要用浏览器代理插件才能进行翻墙~~~

**Comment by louisgry** [comment]
Linux小白同样遇到相同问题，求大神帮助。

**Comment by louisgry** [comment]
IPv6 not support
INFO: loading config from /home/louis/.config/electron-ssr/shadowsocksr.json
ERROR: server addr not specified

**Comment by ATFieldBeast** [comment]
我就是一步一步来的，还是不行，不知道为啥。。。放弃了，用路由器挂着凑合了，谢谢大家啦~

**Comment by erguotou520** [comment]
请大家使用新的0.2.0版本 应该没那么多问题

**Comment by erguotou520** [comment]
先关了，如果有后续问题再开
