### ISSUE TITLE
ubuntu下提示method auth_chain_a not supported

### ISSUE THREAD

**Issue by kkzliu** [erguotou520/electron-ssr#45]
shadowsocksr是从这里clone https://github.com/shadowsocksr-backup/shadowsocksr/
 ~/.config/electron-ssr/shadowsocksr.json配置如下
{
  "server": "server.com",
  "local_address": "127.0.0.1",
  "local_port": 8087,
  "method": "chacha20",
  "obfs": "tls1.2_ticket_auth",
  "obfsparam": "",
  "password": "xxxx",
  "server_port": 10089,
  "protocol": "auth_chain_a",
  "remark": ""
}

运行 python local.py -c ~/.config/electron-ssr/shadowsocksr.json ,报错如下
2017-10-24 15:51:01 INFO     loading libsodium from libsodium.so.18
2017-10-24 15:51:01 INFO     starting local at 127.0.0.1:8087
2017-10-24 15:51:01 ERROR    method auth_chain_a not supported
请问一下是什么原因,谢谢

**Comment by kkzliu** [comment]
执行如下,提示-O无效参数
python /home/xxx/electron-ssr-0.1.2/shadowsocksr/shadowsocks/local.py -s server.com -p 10089 -b 127.0.0.1 -l 8087 -k xxxx -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth
IPv6 not support
option -O not recognized
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address
  -p SERVER_PORT         server port, default: 8388
  -b LOCAL_ADDR          local binding address, default: 127.0.0.1
  -l LOCAL_PORT          local port, default: 1080
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

**Comment by erguotou520** [comment]
这个得看你下载的SSR的文档 看它支不支持正确运行客户端日志里的命令

**Comment by kkzliu** [comment]
已解决, 换ssr就行了,https://github.com/shadowsocksrr/shadowsocksr.git
