### ISSUE TITLE
option -O not recognized

### ISSUE THREAD

**Issue by Ausp1cious** [erguotou520/electron-ssr#46]
日志是这样的：
2017-11-1 13:39:57 stderr:
option -O not recognized
2017-11-1 13:39:57 stdout:
IPv6 support
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address
  -p SERVER_PORT         server port, default: 8388
  -b LOCAL_ADDR          local binding address, default: 127.0.0.1
  -l LOCAL_PORT          local port, default: 1080
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

Online help: <https://github.com/shadowsocks/shadowsocks>

**Comment by erguotou520** [comment]
应该是你的ssr版本不支持`-O`参数 ，`-O`是协议参数，请更新`ssr-python`

**Comment by Ausp1cious** [comment]
谢谢。下载了最新的版本后，就好了。 
还有就是链接后没有响应的问题，通过浏览器设置代理解决了。
