### ISSUE TITLE
Difference between shadowsocks-qt and electron-ssr

### ISSUE THREAD

**Issue by baimafeima** [erguotou520/electron-ssr#49]
What is the difference between https://github.com/shadowsocks/shadowsocks-qt5 and electron-srr? Both are clients to be used on a Linux-based desktop operating system, right?

**Comment by erguotou520** [comment]
I haven't used `shadowsocks-qt5`. But `shadowsocks-qt5` is for `ss` while `electron-ssr` is for `ssr`. `shadowsocks-qt5` writing with c++ while `electron-ssr` writing with nodejs. And `electron-ssr` is not an offcial project. Thanks for your attention。

**Comment by baimafeima** [comment]
I see, thank you for your quick reply. Do you know who is currently working on `ssr`? I've heard that the repository was removed and now there are just several forks. Is there an official project lead with `ssr` that you could refer me to?

Concerning `electron-ssr`, can you confirm that it works on Linux-based operating systems? If yes, then it would make sense to have it included in the repositories of my operating system of choice.

**Comment by erguotou520** [comment]
The author of `ssr` is breakwa11. But she dropped the repository for some reason and is not working on this project as I known. There're only some forks project now. Maybe you can see https://github.com/shadowsocksrr/shadowsocksr

I am sure that `electron-ssr` can work on Ubuntu 17.04 as I have tested on it. It can allso work on other linux system theoretically.

**Comment by baimafeima** [comment]
@erguotou520 Great to know that `electron-ssr` would work with a Linux-based operating system. To be sure, is it essentially a client which allows to connect to a shadowsocks server, similar to if I were using `shadowsocks-qt5`?

**Comment by erguotou520** [comment]
First, `electron-ssr` is a gui client that wraps the `ShadowsocksR` python client.
Then, `electron-ssr` also support `shadowsocks` server.

**Comment by erguotou520** [comment]
Are u Chinese?
`白马非马`

**Comment by wisdomff** [comment]
兩位拼音ID英文對話，忍不住笑一會兒～
