### ISSUE TITLE
How to build ssr in Kali Linux?

### ISSUE THREAD

**Issue by beesuns** [erguotou520/electron-ssr#50]
I am a new Kali Linux user. I run Kali in a live usb drive and my version is 
Linux kali 4.12.0-kali1-amd64 #1 SMP Debian 4.12.6-1kali6 (2017-08-30) x86_64 GNU/Linux
I want to build ssr using the code provided here. And I have a few questions:
1. Which file should I download? .zip, .rpm, .dmg...? I am totally confused.
2. I tried using the source code (.zip file) BUT don't know how to use it. Could any one tell me how to do it?

**Comment by erguotou520** [comment]
I don't know much about Linux Desktop as I use Mac and Windows often. Linux user should download `.rpm` or `.tar.gz` to use. You should search to how to use these file yourself. I will add `.deb` release in the next version in addition.

**Comment by beesuns** [comment]
Thanks for your reply.
I downloaded tar.gz file and tried to install ssr in Kali Linux. When I run ./electron-ssr the following message showed:

请选择shadowsocksr/shadowsocks的目录，如本地没有该目录，请前往https://github.com/shadowsocksr/shadowsocksr下载。请确保该目录下有local.py

However, this url didn't work. It showed "Page not found". 
How can I get this directory and the local.py file?

**Comment by erguotou520** [comment]
Sorry, the `shadowsocksr` project was removed for some reason. Maybe you can try some backups like `https://github.com/shadowsocksrr/shadowsocksr`(I am not sure this can work).  
The `local.py` is under `shadowsocks` folder which is contained in the `shadowsocksr`'s project.

**Comment by erguotou520** [comment]
Hey, try to use `0.2.0-beta-1` release. It will download `ssr` automatically.
