### ISSUE TITLE
ubuntu 16.04显示不出界面和小图标

### ISSUE THREAD

**Issue by a7859696** [erguotou520/electron-ssr#51]
第一次使用软件时，能显示出界面。但是关机过了一晚之后，再点击就没有界面和小图标出来了

试了用sudo启动也没有
Config file's path: /home/li/.config/electron-ssr/shadowsocksr.json
/home/li/svn/shadowsocksr/shadowsocks/local.py
mainWindow opened

用鼠标点击启动，显示有4个electron-ssr进程。但是也没有界面出来

**Comment by kid1412621** [comment]
17.10 表示 0.1.1 不能打开界面

**Comment by pengcheng789** [comment]
17.10 表示相同bug，第一次有界面，随后几次就没有了。

**Comment by KGWKenta** [comment]
17.10 表示+1

**Comment by jacknesstjh** [comment]
arch表示也是这样 第一次有界面 后来点击各种都无效。求解决方案

**Comment by HuangBoHong** [comment]
+1

**Comment by erguotou520** [comment]
下个版本会有大量变更，尝试修复这个问题

**Comment by jingle0927** [comment]
能打包个deb吗

**Comment by erguotou520** [comment]
@jingle0927 先用rpm或者什么的转下吧 最近在维护新版

**Comment by erguotou520** [comment]
@jingle0927 打了个临时的0.1.3版本

**Comment by erguotou520** [comment]
请大家试用下新的`beta`版本，然后反馈下是否还有这个问题

**Comment by fzsimlu** [comment]
ubuntu18.04下面还是会，安装了libappindicator1应用程序指示器也不行，其他人有没遇到过。
功能在界面看到不
