### ISSUE TITLE
無法切換服務器

### ISSUE THREAD

**Issue by Fe1IYang** [erguotou520/electron-ssr#52]
系統：Deepin 15
Python版本：2.7.13
在服務器選單內有兩個服務器時，只能使用第一個服務器，切換到第二個服務器無效，試過重新開啓代理，退出重開。
雖然終端窗內的指令日誌顯示執行的是鏈接第二個服務器，但在IPIP.NET查看發現IP仍舊是第一個服務器的IP，求解決。

**Comment by erguotou520** [comment]
问题应该已修复，请核实
