### ISSUE TITLE
你好 我這邊運行app配置完成 無法使用 求解

### ISSUE THREAD

**Issue by azhm** [erguotou520/electron-ssr#53]
hello 你好 我這邊查看日誌報錯沒有配置 但是我已經配置過服務器了 
求解 感謝 以下是日誌部分訊息

2017-12-9 22:33:43 stdout:
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.
- 

-

**Comment by erguotou520** [comment]
这个我就不太清楚了，建议你先用命令行试试，然后去ssr那边问问

**Comment by azhm** [comment]
你好 Mac程序运行正常 为什么不能直接访问外网 
还得浏览器代理sock5 才能访问外网？

**Comment by erguotou520** [comment]
@azhm 默认应该是可以的，不知道你用的什么浏览器？有没有其它什么设置覆盖了？有没有设置浏览器的代理？比如chrome的`Proxy SwitchShape`就可以添加代理。

**Comment by azhm** [comment]
我用的chrome 
没有使用其他代理工具
os 10.13.1 
打开程序后无法FQ 还是要配置socks5代理 127.0.01 1080 才能正常FQ 
大噶是什么原因呢 能否留一个联系方式tg or wx 有偿请教.. 
感谢老哥

**Comment by erguotou520** [comment]
你在哪里设置的socks5代理？是chrome的插件？

**Comment by azhm** [comment]
我浏览器用的SwitchyOmega

**Comment by erguotou520** [comment]
这种情况下确实需要设置代理呢

**Comment by azhm** [comment]
有无办法可以开了程序 就可以FQ呢？

**Comment by erguotou520** [comment]
`SwitchyOmega`选择`使用系统代理设置`。本身这个插件就是为了管理哪些网站f，哪些网站不f的，建议你使用插件来管理比较好。

**Comment by azhm** [comment]
原版小飞机是通过什么方式 实现打开了软件直接可以电脑全局FQ的呢？

**Comment by erguotou520** [comment]
不管什么版本的小飞机都是提供socks5的方式，如果chrome不安装什么fq管理工具是可以实现
> 打开了软件直接可以电脑全局FQ的呢
的，但是你安装了插件后就要按照插件的来

**Comment by azhm** [comment]
我现在想实现不通过安装其他软件 打开程序就能FQ 有办法实现吗？

**Comment by erguotou520** [comment]
移除插件就可以了 或者使用safari查看效果

**Comment by azhm** [comment]
移除插件就不能FQ了呢 现在问题就是这个

**Comment by erguotou520** [comment]
选择你的网络连接，点击“高级”，切换到“代理”选项卡，勾选为“socks代理“并填写地址为`127.0.0.1:1080`试试？

**Comment by erguotou520** [comment]
因为我这个项目没有提供pac的方式，所以填写socks方式试试

**Comment by azhm** [comment]
@erguotou520 选择你的网络连接，点击“高级”，切换到“代理”选项卡，勾选为“socks代理“并填写地址为127.0.0.1:1080试试？

你说的那种方法配置了可行 ,  但是有无办法可以不需要手动去配置 
在软件端直接配置好呢

**Comment by erguotou520** [comment]
目前并没有，因为底层使用的是ssr的python版，它只是提供了一个socks5的代理而已

**Comment by azhm** [comment]
好嘛...
还有一个问题  我能否打包app的时候将local.py目录一起打包 
新安装app就不用在手动选择位置？是否可行呢

**Comment by erguotou520** [comment]
呃，之前的版本是这么做的，但是考虑到解耦，所以改成了让用户手动选择，而且更新也方便，这也是用户提出的建议。

如果你非要一起打包的话，建议你两个项目一起打包成zip

另外下个版本尝试加入pac功能，可以实现你之前的需求（目前只是有这个功能加入的打算）

**Comment by azhm** [comment]
因为很多用户他不知道这是个啥玩意 也没有下载这个包
所以我想准备打包集成一起 
下个版本加入pac就可以 直接就可以不需要配置网络socks代理了？
还是想求个联系方式 thanks u.

**Comment by erguotou520** [comment]
邮件 erguotou525@gmail.com 发我你的wx二维码

**Comment by erguotou520** [comment]
如果项目对你有所帮助，欢迎来打赏 😄 
https://github.com/erguotou520/donate

**Comment by azhm** [comment]
ok 感谢老哥 已发 
必定打赏

**Comment by Gux12** [comment]
我也有相同的问题
如何才能像其他原版的ss客户端一样
开启代理的时候就可以将系统的代理一同打开
我觉得可能只能用node执行一个子进程来实现了...

**Comment by Gux12** [comment]
@azhm https://dmorgan.info/posts/mac-network-proxy-terminal/
这个可能会对你有帮助，win暂时不太清楚

**Comment by erguotou520** [comment]
@Gux12 该功能已有调查和实验，https://github.com/erguotou520/electron-ssr/blob/redesign/docs/AUTO_PROXY.md 该功能将在下一个大版中添加

**Comment by Gux12** [comment]
@erguotou520 b(￣▽￣)d

**Comment by erguotou520** [comment]
@Gux12 欢迎加入TG群一起讨论
https://t.me/joinchat/E7ViZhJAZpKtnIJy9WepDA

**Comment by erguotou520** [comment]
`0.2.0`版本中已实现
