### ISSUE TITLE
0.1.3版本报-O 选项错误

### ISSUE THREAD

**Issue by zhangkuanyi** [erguotou520/electron-ssr#55]
作者你好，本人在Ubuntu16.04 系统下成功配置了该软件的安装环境，但是每次链接都会报错：
显示-O选项未识别
2018-1-17 16:47:11 stderr:
option -O not recognized
2018-1-17 16:47:11 stdout:
IPv6 not support
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

PS：曾经尝试过在shadowsocks-qt5里面直接导入json文件，显示已经连接但是实际上并没有连接上，服务器测试没问题。

**Comment by erguotou520** [comment]
1. 截图中最好打码
2. `-O`未识别的话应该是`shadowsocksr-python`版本比较低，建议升级
3. 欢迎加入TG讨论组 https://t.me/joinchat/E7ViZhJAZpKtnIJy9WepDA

**Comment by zhangkuanyi** [comment]
感谢作者，已经解决，是版本太旧导致的obfs.py文件不能识别
