### ISSUE TITLE
'&' in password broke the local.py command line

### ISSUE THREAD

**Issue by MyonKeminta** [erguotou520/electron-ssr#61]
Ubuntu 16.04

Version: 0.2.0-alpha-4

My password contains a `&`, which broke the execution command line of `local.py` of ssr.

Maybe it's better to wrap the password with a pair of single quote marks, at least on Linux.

Or, maybe there exist some way to pass command line args directly to the process?

Log:
```
2018-01-27T17:47:35+0800 <debug> main.js:1 (n) run command: python "/home/xxxx/.config/electron-ssr/shadowsocksr/shadowsocks/local.py" -s xxx.xxx.xxx.xxx -p xxxx -k aaaa&bbbb -m xxxx -O xxxx -o xxxx -b 127.0.0.1 -l 1080 --log-file /home/xxxx/.config/electron-ssr/logs/shadowsocksr.log
2018-01-27T17:47:35+0800 <error> events.js:101 (emitOne) /bin/sh: 1: bbbb not found
```

**Comment by erguotou520** [comment]
Yes, good suggestion.

**Comment by erguotou520** [comment]
The same with `protocolparam` and `obfs_param`

**Comment by MyonKeminta** [comment]
....if wrap the password with single quote marks, there may be single quote marks in the password

**Comment by erguotou520** [comment]
so what's your suggestion?

**Comment by MyonKeminta** [comment]
I saw document of `child_process.exec` and found:

> Note: Never pass unsanitised user input to this function. Any input containing shell metacharacters may be used to trigger arbitrary command execution.

I think maybe you can use `child_process.execFile` instead.

**Comment by erguotou520** [comment]
#https://github.com/erguotou520/electron-ssr/commit/6dc0c2bf570feccb8b4e1154e6b621516ae40723#diff-9ac84e435546871b9428fc9672c2e003R16

**Comment by erguotou520** [comment]
https://github.com/erguotou520/electron-ssr/commit/6dc0c2bf570feccb8b4e1154e6b621516ae40723#diff-9ac84e435546871b9428fc9672c2e003R16
