### ISSUE TITLE
不支持插件auth_chain_b

### ISSUE THREAD

**Issue by alwzying** [erguotou520/electron-ssr#62]
2018-01-28 10:07:20 ERROR    shell.py:50 obfs plugin [auth_chain_b] not supported

**Comment by erguotou520** [comment]
请升级你自己的shadowsocksr-python代码

**Comment by JoeyLi-1** [comment]
@erguotou520 求教！我服务器是按这个部的（https://shadowsocks.be/9.html），客户端windows（windows不是用这个客户端）正常使用，用mac就提示shell.py:50 obfs plugin [auth_chain_b] not supported，该怎么升级shadowsocksr-python代码啊？
