### ISSUE TITLE
electron-ssr加密和协议支持咨询

### ISSUE THREAD

**Issue by sysconfon** [erguotou520/electron-ssr#65]
加密方式内是否能加入：none加密呢？
加密协议这块是否能加入：auth_chain_a 等协议的呢？
可参考链接：https://doub.io/ss-jc54/

**Comment by erguotou520** [comment]
请自行在应用内添加。
`0.1.x`版本直接修改配置文件
`0.2.x`版本请右击任务栏图标-配置-选项设置...，然后切换到`SSR设置`选项卡中自行添加。

该问题将同步到FAQ中，同时更新代码内默认协议。
