### ISSUE TITLE
关于混淆参数的bug

### ISSUE THREAD

**Issue by updater1234** [erguotou520/electron-ssr#66]
## Your os

Linuxmint18.3
## The version of electron-ssr

0.2-beta-1
## What's the problem

混淆参数填写了混淆域名，但是日志里的obfs_param却是空的。
## App log here

![2](https://user-images.githubusercontent.com/31512600/35571532-57fed6b2-060d-11e8-9de9-0eb8fe45185e.png)
![1](https://user-images.githubusercontent.com/31512600/35571543-60e16ccc-060d-11e8-8575-8b6d79efe365.png)

**Comment by erguotou520** [comment]
你看下前面的日志 是否有`-g 你的obfs_param`？

**Comment by erguotou520** [comment]
beta2已修复

**Comment by updater1234** [comment]
那好，谢谢。
