### ISSUE TITLE
取消勾选 http 代理，保存退出软件，再打开进入设置，http 代理又被勾选

### ISSUE THREAD

**Issue by kid1412621** [erguotou520/electron-ssr#67]
## Your os

Windows 
## The version of electron-ssr

0.2.0-beta-1
## What's the problem

取消勾选 http 代理，保存退出软件，再打开进入设置，http 代理又被勾选.
## App log here

![image](https://user-images.githubusercontent.com/26278054/35603292-b4f9e680-0677-11e8-9435-e5f46b2c1f4c.png)

**Comment by erguotou520** [comment]
beta2已修复
