### ISSUE TITLE
Arch Linux 上遇到的问题

### ISSUE THREAD

**Issue by Yves0** [erguotou520/electron-ssr#69]
## OS
ArchLinux

## The version of electron-ssr
0.2.0

## What's the problem
- ~~kill 进程之后 Python 进程还存活，再次打开无法点击，杀死 Python 进程之后恢复正常~~
- ~~扫描二维码时，如果扫描失败（如屏幕没有二维码）之后卡死，**有时卡死容易导致整个桌面都无法点击**，只能进入其他 tty 杀死进程~~
- ~~i3wm 上托盘图标不显示，但可以点击~~
- ~~扫描二维码无法添加服务器，添加的是重复的记录~~
- ~~可以打开多个 App 实例~~

**Comment by Yves0** [comment]
我是从 deb 包手动移植到 Arch 上的

**Comment by erguotou520** [comment]
不是有pacman么

**Comment by Yves0** [comment]
很抱歉刚刚没有看到 pacman 的包。刚刚下载安装了，点击扫描二维码之后就卡住了，一段时间后恢复，但不影响桌面其他程序的点击事件。托盘图标依旧不显示

**Comment by Yves0** [comment]
# 更新 v0.2.0-beta-5 之后存在的问题：
- 小概率事件：无法通过扫描二维码添加节点，重启后恢复正常
![](http://ws3.sinaimg.cn/large/006pLqqCgy1foh8pz4mypj30a601rwef.jpg)
- 反复扫描会重复添加节点
- 无法删除分组及其所有节点，需要逐个删除节点
- 节点连接失败时不断弹出 log 窗口

**Comment by erguotou520** [comment]
- 二维码扫描请保证屏幕中只有一个可见的正确的二维码
- 确实是这样的，就是这么设计的
- 已证实，马上修
- 确实是这样的，下个版本不会弹了

**Comment by erguotou520** [comment]
后2点在`0.2.0`中已修改
