### ISSUE TITLE
建议在主界面添加设置按钮

### ISSUE THREAD

**Issue by kid1412621** [erguotou520/electron-ssr#71]
## Your os

Win 10
## The version of electron-ssr

v0.2.0 beta-2
## What's the problem

在服务器列表界面添加设置按钮，这样就可以在主界面和设置界面来回切换，而不用去托盘图标菜单再次进入。
![1](https://user-images.githubusercontent.com/26278054/35840398-ff3dbfe2-0b30-11e8-918c-a1676cc772e9.png)
                                             |                                                          ^
                                             |                                                           |
                                             x                                                          | 
                                             |                                                           |
                                            V                                                           |
![2](https://user-images.githubusercontent.com/26278054/35840400-017573f4-0b31-11e8-8f99-7c9c2199e172.png)

**Comment by erguotou520** [comment]
目前通过添加后面的下拉可以跳到选项设置，设置页面点击返回可以返回主页面
