### ISSUE TITLE
elementary os 无法启动。。

### ISSUE THREAD

**Issue by BKDOnions** [erguotou520/electron-ssr#74]

**Comment by erguotou520** [comment]
请描述清除问题 否则将关闭issue

**Comment by BKDOnions** [comment]
???根本打不开

**Comment by erguotou520** [comment]
你先试下AppImage版本

**Comment by MaksimChan** [comment]
我也有遇见这个问题，kali系统，root账户，第一次ui出现了，也可以进行操作，但是添加不了服务器（添加后自动变成默认），我就试着重新开一遍，然后就在打不开了，kill也不行重启也不行

**Comment by erguotou520** [comment]
日志有没有啥报错？

**Comment by erguotou520** [comment]
linux衍生版太多 我没办法一个一个测试，所以有问题的时候最好把日志内容也一起发下 这样有助于判断

**Comment by erguotou520** [comment]
先关issue，有详细信息再开
