### ISSUE TITLE
manjaro不能翻？

### ISSUE THREAD

**Issue by adaaaaaa** [erguotou520/electron-ssr#75]
manjaro是基于arch的。。。switchyomega怎么调都不行，默认也没用。。。
大佬看看日志，有什么问题吗？

这个系统安装最新的软件是不是用XXX.pacman那个包？要用什么命令安装？

**Comment by adaaaaaa** [comment]
这个系统安装最新的软件是不是用XXX.pacman那个包？要用什么命令安装？

**Comment by updater1234** [comment]
我也是用manjaro,我的可以啊。

**Comment by adaaaaaa** [comment]
出来更新订阅服务器，还需要怎么设置吗？@updater1234

**Comment by adaaaaaa** [comment]
.pacman那个文件是可以给manjaro安装的吗？怎么装？@updater1234

**Comment by updater1234** [comment]
这个不清楚，我用的是appimage。

**Comment by erguotou520** [comment]
1. 请移除日志文件中的重要信息！
2. 日志并没有报错内容，请尝试复制run command后的命令到terminal中直接运行看是否能fq
3. pacman文件是给arch用的，优先推荐使用appimage

**Comment by adaaaaaa** [comment]
成功鸟。。。主要是switchyomega没有设置好。。。
可以贡献个switchyomega的备份文件吗？ @erguotou520

**Comment by erguotou520** [comment]
没有 23333

**Comment by zgat** [comment]
我也是manjaro,请问你们是怎么弄的

**Comment by zgat** [comment]
我也是manjaro,run conmmand执行的结果是

**Comment by zgat** [comment]
`IPv6 support2018-05-14 17:42:50 ERROR    shell.py:93 password not specifiedusage: sslocal [OPTION]...A fast tunnel proxy that helps you bypass firewalls.You can supply configurations via either config file or command line arguments.Proxy options:  -c CONFIG              path to config file  -s SERVER_ADDR         server address  -p SERVER_PORT         server port, default: 8388  -b LOCAL_ADDR          local binding address, default: 127.0.0.1  -l LOCAL_PORT          local port, default: 1080  -k PASSWORD            password  -m METHOD              encryption method, default: aes-256-cfb  -o OBFS                obfsplugin, default: http_simple  -t TIMEOUT             timeout in seconds, default: 300  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+General options:  -h, --help             show this help message and exit  -d start/stop/restart  daemon mode  --pid-file PID_FILE    pid file for daemon mode  --log-file LOG_FILE    log file for daemon mode  --user USER            username to run as  -v, -vv                verbose mode  -q, -qq                quiet mode, only show warnings/errors  --version              show version informationOnline help: <https://github.com/shadowsocks/shadowsocks>`

**Comment by zgat** [comment]
我也是manajro不能翻

**Comment by zgat** [comment]
我也是manjaro不能翻
run command的执行结果如下
`IPv6 support
2018-05-14 17:42:50 ERROR    shell.py:93 password not specified
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address
  -p SERVER_PORT         server port, default: 8388
  -b LOCAL_ADDR          local binding address, default: 127.0.0.1
  -l LOCAL_PORT          local port, default: 1080
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

Online help: <https://github.com/shadowsocks/shadowsocks>
`

**Comment by zgat** [comment]
刚刚发现FireFox出去了.Chrome不行...我研究一下

**Comment by erguotou520** [comment]
@zgat 我日志中特意去掉了密码 你在执行command时把密码参数加上`-k password`

**Comment by zgat** [comment]
```
IPv6 support
2018-05-18 15:38:55 WARNING  shell.py:110 warning: local set to listen on 0.0.0.0, it's not safe
2018-05-18 15:38:55 INFO     local.py:50 local start with protocol[auth_chain_a] password [*******] method [none] obfs [http_simple] obfs_param []
2018-05-18 15:38:55 INFO     local.py:54 starting local at 0.0.0.0:1080
2018-05-18 15:38:55 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]
Mint 的执行结果
```
```
IPv6 support
2018-05-18 23:42:15 INFO     local.py:50 local start with protocol[auth_chain_a] password [b'*******'] method [none] obfs [http_simple] obfs_param []
2018-05-18 23:42:15 INFO     local.py:54 starting local at 0.0.0.0:1080
2018-05-18 23:42:15 INFO     asyncdns.py:324 dns server: [('223.5.5.5', 53), ('223.6.6.6', 53)]
Manjaro的执行结果
```

**Comment by erguotou520** [comment]
并没有问题的样子

**Comment by zgat** [comment]
但是Manjaro用Chrome死活都在墙内..

**Comment by erguotou520** [comment]
这个要综合查看chrome的代理设置

**Comment by zgat** [comment]
我有这么想过,但我用Linux和Manjro打开Chrome的代理模式都是给了相同的提示
在受支持的桌面环境中运行Google Chrome时，将使用系统代理设置。但您的系统不受支持，或启动系统配置时出现问题。

但您仍可通过命令行进行配置。如需详细了解各项实验功能和环境变量，请参见 man google-chrome-stable。

**Comment by zgat** [comment]
另外刚刚发现Firefox也在墙内了,笑哭

**Comment by erguotou520** [comment]
验证的方法是 点击菜单"复制http代理设置" 然后在terminal中粘贴 然后使用 `curl www.google.com`命令试下能否访问，如果不能请再次附上日志

**Comment by zgat** [comment]
访问成功 emmm

**Comment by erguotou520** [comment]
那说明是浏览器代理问题

**Comment by zgat** [comment]
看来就是chrome的问题,我再研究研究
