### ISSUE TITLE
kali linux启动报错

### ISSUE THREAD

**Issue by hxcc** [erguotou520/electron-ssr#90]
## 

kali linux
## What's the problem

启动报错，安装后点击图标启动就直接空白，另外有tg群顺便发我个
## App log here

![123](https://user-images.githubusercontent.com/16927370/37981283-d704c028-321f-11e8-8b07-d53774e5b5e6.png)

**Comment by hxcc** [comment]
ubuntu可以正常运行，kali 不行

**Comment by erguotou520** [comment]
试试用.AppImage运行
