### ISSUE TITLE
关于Linux非gnome系统代理的实现

### ISSUE THREAD

**Issue by Howard-00** [erguotou520/electron-ssr#93]
（本人使用的是xfce4）由于在连接管理器中可设置PAC地址，理论上应该可以通过修改PAC文件来切换代理模式。
在系统中手动设置PAC为127.0.0.1:2333，软件中则内置gfwlist、全部走代理和全部不走代理三种PAC，通过替换PAC文件实现对系统代理的控制

**Comment by erguotou520** [comment]
你说的跟我实现的是2种方式，一种是依赖系统去实现，一种是所有请求走代理，然后在应用内实现哪些走代理，目前暂不考虑更换模式。
另外我说的非gnome系统切换是指自动实现的方式，即可以通过命令行实现的方式。

**Comment by erguotou520** [comment]
如果有更进一步的补充或建议再开issue
