### ISSUE TITLE
是否可以自动检测并安装 libsodium？

### ISSUE THREAD

**Issue by lslzl3000** [erguotou520/electron-ssr#94]
是否可以检测一下libsodium，并且自动帮用户下载安装？

**Comment by lslzl3000** [comment]
或者直接把所有libsodium的打包到客户端里，用chacha20的人还挺多的，我这边的服务器基本都是chacha20，用户都用不了

**Comment by erguotou520** [comment]
可以考虑加入，但是要先研究：
1. 跨平台如何判断是否安装了`libsodium`？
2. 跨平台如何安装`libsodium`？

**Comment by lslzl3000** [comment]
查了一下libsodium，其实文件不多，也不大
1. ssr 的 util.py 中就有检查各种lib的路径方法，就是检查path
2. 理论上自动下载各平台的 .so/.dll/.dylib等编译好的版本，window的话，把dll copy 到system32中，mac/linux 把libsodium的path export一下，应该就可以完成安装

**Comment by lslzl3000** [comment]
不花精力搞python了，直接用libev的客户端~
