### ISSUE TITLE
同样的主机,electron链接较慢,经常卡,经常没反应.

### ISSUE THREAD

**Issue by issuessss** [erguotou520/electron-ssr#98]
同样的主机,electron链接很慢,很卡,经常没反应.非常明显.
我的直觉是干扰非常严重, 不知道是不是dns问题.
macos 10.13.4
electron-ssr 0.2.3

**Comment by erguotou520** [comment]
直接使用python命令行运行呢？

**Comment by 0400H** [comment]
please find "LOL/electron-ssr/shadowsocksr/config.json"
then change "timeout": 500,  "udp_timeout": 500, or for more
if u use switchyomega, please use proxy rather than autoswitch

**Comment by erguotou520** [comment]
在提供更进一步的信息之前将关闭issue
