### ISSUE TITLE
关于快捷键

### ISSUE THREAD

**Issue by Lookingfor0** [erguotou520/electron-ssr#99]
Linux平台
Ctrl+Shift+W会打开设置界面，经常不经意间打开客户端
请问能否关闭全局快捷键或者设置快捷键？

**Comment by erguotou520** [comment]
暂时没有提供该功能，后续会加入

**Comment by simon300000** [comment]
我试试看能不能加入→_→

**Comment by idnsunset** [comment]
请问快捷键的自定义功能预计在哪个版本中加入？用了 0.2.4 版本，发现问题如下：
- 键入 `ctrl-shift-w` 无效，配置窗口并未打开。
- electron-ssr 运行时，chrome 无法使用 `ctrl-shift-b` toggle boomark bar 。
另外在 chrome 中 `ctrl-shift-w` 是关闭当前窗口，在 terminal 中是关闭当前 tab，还有不少软件都绑定了这个快捷键，所以自定义快捷键的功能非常必要，至少要能禁用。

**Comment by erguotou520** [comment]
0.2.4没加这个功能，且只有linux能用`ctrl-shift-b`

**Comment by erguotou520** [comment]
0.2.5已加入自定义快捷键

**Comment by erguotou520** [comment]
已确定这是一个Bug，下个版本修复，目前可以忽略或者设置不冲突的快捷键
